#!/usr/bin/env bash
set -euo pipefail

required_files=(
  docs/20-domain/context-map.md
  docs/20-domain/context-map.riido.json
  docs/20-domain/context-map/acl-locations.riido.json
  docs/20-domain/context-map/change-procedure.riido.json
  docs/20-domain/context-map/dependency-direction.riido.json
  docs/20-domain/context-map/figma-daemon-boundaries.riido.json
  docs/20-domain/context-map/figma-onboarding-boundaries.riido.json
  docs/20-domain/context-map/split-repo-ownership.riido.json
  .github/workflows/context-map-docs.yml
  docs/20-domain/locking.md
  docs/20-domain/locking.riido.json
  docs/20-domain/locking/local-file-lock.md
  docs/20-domain/locking/local-file-lock.riido.json
  docs/20-domain/locking/lease-registry.md
  docs/20-domain/locking/lease-registry.riido.json
  docs/20-domain/locking/acquire-release.md
  docs/20-domain/locking/acquire-release.riido.json
  docs/20-domain/locking/request-metadata.md
  docs/20-domain/locking/request-metadata.riido.json
  docs/20-domain/locking/adjacent-contracts.md
  docs/20-domain/locking/adjacent-contracts.riido.json
  .github/workflows/locking-docs.yml
  docs/20-domain/security-redaction.md
  docs/20-domain/security-redaction.riido.json
  docs/20-domain/security-redaction/audit-event.md
  docs/20-domain/security-redaction/audit-event.riido.json
  docs/20-domain/security-redaction/execution-responsibility.md
  docs/20-domain/security-redaction/execution-responsibility.riido.json
  docs/20-domain/security-redaction/failure.md
  docs/20-domain/security-redaction/failure.riido.json
  docs/20-domain/security-redaction/markers.md
  docs/20-domain/security-redaction/markers.riido.json
  docs/20-domain/security-redaction/pattern-catalog.md
  docs/20-domain/security-redaction/pattern-catalog.riido.json
  docs/20-domain/security-redaction/verification-gates.md
  docs/20-domain/security-redaction/verification-gates.riido.json
  docs/20-domain/security-redaction/versioning.md
  docs/20-domain/security-redaction/versioning.riido.json
  .github/workflows/security-redaction-docs.yml
  docs/20-domain/security.md
  docs/20-domain/security.riido.json
  docs/20-domain/security/enforcement-locations.md
  docs/20-domain/security/enforcement-locations.riido.json
  docs/20-domain/security/enforcement-locations/audit-and-contracts.md
  docs/20-domain/security/enforcement-locations/audit-and-contracts.riido.json
  docs/20-domain/security/enforcement-locations/open-issues-and-versioning.md
  docs/20-domain/security/enforcement-locations/open-issues-and-versioning.riido.json
  .github/workflows/security-docs.yml
  docs/20-domain/security/invariants.md
  docs/20-domain/security/invariants.riido.json
  docs/20-domain/security/invariants/scope.md
  docs/20-domain/security/invariants/scope.riido.json
  docs/20-domain/security/invariants/core.md
  docs/20-domain/security/invariants/core.riido.json
  docs/20-domain/security/invariants/trust-tier.md
  docs/20-domain/security/invariants/trust-tier.riido.json
  docs/20-domain/security/invariants/policy-bundle-model.md
  docs/20-domain/security/invariants/policy-bundle-model.riido.json
  docs/20-domain/security/invariants/policy-bundle-example.md
  docs/20-domain/security/invariants/policy-bundle-example.riido.json
  docs/20-domain/security/invariants/policy-targets.md
  docs/20-domain/security/invariants/policy-targets.riido.json
  .github/workflows/security-invariants-docs.yml
  docs/20-domain/security/native-config-overlay.md
  docs/20-domain/security/native-config-overlay.riido.json
  docs/20-domain/security/native-config-overlay/overlay-decision.md
  docs/20-domain/security/native-config-overlay/overlay-decision.riido.json
  docs/20-domain/security/native-config-overlay/runtime-secret-evidence.md
  docs/20-domain/security/native-config-overlay/runtime-secret-evidence.riido.json
  docs/20-domain/security/native-config-overlay/security-gates.md
  docs/20-domain/security/native-config-overlay/security-gates.riido.json
  docs/20-domain/security/native-config-overlay/store-channel-policy-gate.md
  docs/20-domain/security/native-config-overlay/store-channel-policy-gate.riido.json
  docs/20-domain/security/native-config-overlay/gate-result-ir.md
  docs/20-domain/security/native-config-overlay/gate-result-ir.riido.json
  docs/20-domain/security/native-config-overlay/unsafe-bypass-policy.md
  docs/20-domain/security/native-config-overlay/unsafe-bypass-policy.riido.json
  .github/workflows/security-native-config-overlay-docs.yml
  docs/20-domain/provider-runtime.md
  docs/20-domain/provider-runtime.riido.json
  docs/20-domain/provider-runtime/overview.md
  docs/20-domain/provider-runtime/overview.riido.json
  docs/20-domain/provider-runtime/adapter-draft-fields.md
  docs/20-domain/provider-runtime/adapter-draft-fields.riido.json
  docs/20-domain/provider-runtime/versioning.md
  docs/20-domain/provider-runtime/versioning.riido.json
  .github/workflows/provider-runtime-docs.yml
  docs/20-domain/provider-runtime/runtime-responsibility.md
  docs/20-domain/provider-runtime/runtime-responsibility.riido.json
  docs/20-domain/provider-runtime/runtime-responsibility/responsibility-statement.md
  docs/20-domain/provider-runtime/runtime-responsibility/responsibility-statement.riido.json
  docs/20-domain/provider-runtime/runtime-responsibility/agent-client-nonresponsibilities.md
  docs/20-domain/provider-runtime/runtime-responsibility/agent-client-nonresponsibilities.riido.json
  docs/20-domain/provider-runtime/runtime-responsibility/figma-task-runtime-boundaries.md
  docs/20-domain/provider-runtime/runtime-responsibility/figma-task-runtime-boundaries.riido.json
  docs/20-domain/provider-runtime/runtime-responsibility/figma-onboarding-settings-boundaries.md
  docs/20-domain/provider-runtime/runtime-responsibility/figma-onboarding-settings-boundaries.riido.json
  docs/20-domain/provider-runtime/runtime-responsibility/domain-nonresponsibilities.md
  docs/20-domain/provider-runtime/runtime-responsibility/domain-nonresponsibilities.riido.json
  docs/20-domain/provider-runtime/runtime-responsibility/c3-c4-boundary.md
  docs/20-domain/provider-runtime/runtime-responsibility/c3-c4-boundary.riido.json
  docs/20-domain/provider-runtime/runtime-responsibility/trusted-runtime-envelope.md
  docs/20-domain/provider-runtime/runtime-responsibility/trusted-runtime-envelope.riido.json
  docs/20-domain/provider-runtime/runtime-responsibility/provider-adapter-port.md
  docs/20-domain/provider-runtime/runtime-responsibility/provider-adapter-port.riido.json
  .github/workflows/provider-runtime-responsibility-docs.yml
  docs/20-domain/provider-runtime/adapter-acl.md
  docs/20-domain/provider-runtime/adapter-acl.riido.json
  docs/20-domain/provider-runtime/adapter-acl/raw-to-draft-rules.md
  docs/20-domain/provider-runtime/adapter-acl/raw-to-draft-rules.riido.json
  docs/20-domain/provider-runtime/adapter-acl/backpressure.md
  docs/20-domain/provider-runtime/adapter-acl/backpressure.riido.json
  docs/20-domain/provider-runtime/adapter-acl/bridge-boundary.md
  docs/20-domain/provider-runtime/adapter-acl/bridge-boundary.riido.json
  docs/20-domain/provider-runtime/adapter-acl/instruction-placement.md
  docs/20-domain/provider-runtime/adapter-acl/instruction-placement.riido.json
  docs/20-domain/provider-runtime/adapter-acl/detect-helper-boundary.md
  docs/20-domain/provider-runtime/adapter-acl/detect-helper-boundary.riido.json
  .github/workflows/provider-adapter-acl-docs.yml
  docs/20-domain/provider-runtime/integration-gates.md
  docs/20-domain/provider-runtime/integration-gates.riido.json
  docs/20-domain/provider-runtime/integration-gates/cursor-real-cli.md
  docs/20-domain/provider-runtime/integration-gates/cursor-real-cli.riido.json
  docs/20-domain/provider-runtime/integration-gates/provider-validation-matrix.md
  docs/20-domain/provider-runtime/integration-gates/provider-validation-matrix.riido.json
  docs/20-domain/provider-runtime/integration-gates/supervisor-scope.md
  docs/20-domain/provider-runtime/integration-gates/supervisor-scope.riido.json
  docs/20-domain/provider-runtime/integration-gates/taskdbplane-scope.md
  docs/20-domain/provider-runtime/integration-gates/taskdbplane-scope.riido.json
  docs/20-domain/provider-runtime/integration-gates/riidoapi-local-api.md
  docs/20-domain/provider-runtime/integration-gates/riidoapi-local-api.riido.json
  docs/20-domain/provider-runtime/integration-gates/mwsd-project-sync.md
  docs/20-domain/provider-runtime/integration-gates/mwsd-project-sync.riido.json
  docs/20-domain/provider-runtime/integration-gates/saasplane-scope.md
  docs/20-domain/provider-runtime/integration-gates/saasplane-scope.riido.json
  docs/20-domain/provider-runtime/integration-gates/saasplane-runtime-snapshot.md
  docs/20-domain/provider-runtime/integration-gates/saasplane-runtime-snapshot.riido.json
  docs/20-domain/provider-runtime/integration-gates/daemon-lifecycle-adapter.md
  docs/20-domain/provider-runtime/integration-gates/daemon-lifecycle-adapter.riido.json
  .github/workflows/provider-integration-gate-docs.yml
  docs/20-domain/provider-runtime/runtime-actor-boundary.md
  docs/20-domain/provider-runtime/runtime-actor-boundary.riido.json
  docs/20-domain/provider-runtime/runtime-actor-boundary/runtime-actor.md
  docs/20-domain/provider-runtime/runtime-actor-boundary/runtime-actor.riido.json
  docs/20-domain/provider-runtime/runtime-actor-boundary/control-plane-port.md
  docs/20-domain/provider-runtime/runtime-actor-boundary/control-plane-port.riido.json
  docs/20-domain/provider-runtime/runtime-actor-boundary/supervisor.md
  docs/20-domain/provider-runtime/runtime-actor-boundary/supervisor.riido.json
  docs/20-domain/provider-runtime/runtime-actor-boundary/provider-session-preservation.md
  docs/20-domain/provider-runtime/runtime-actor-boundary/provider-session-preservation.riido.json
  docs/20-domain/provider-runtime/runtime-actor-boundary/adjacent-ssot-contracts.md
  docs/20-domain/provider-runtime/runtime-actor-boundary/adjacent-ssot-contracts.riido.json
  docs/20-domain/provider-runtime/runtime-actor-boundary/provider-stdin-command-acl.md
  docs/20-domain/provider-runtime/runtime-actor-boundary/provider-stdin-command-acl.riido.json
  docs/20-domain/provider-runtime/runtime-actor-boundary/provider-adapter-implementations.md
  docs/20-domain/provider-runtime/runtime-actor-boundary/provider-adapter-implementations.riido.json
  docs/20-domain/provider-runtime/runtime-actor-boundary/open-issues.md
  docs/20-domain/provider-runtime/runtime-actor-boundary/open-issues.riido.json
  .github/workflows/provider-runtime-boundary-docs.yml
  docs/20-domain/workspace.md
  docs/20-domain/workspace.riido.json
  .github/workflows/workspace-docs.yml
  docs/20-domain/workspace/invariants.md
  docs/20-domain/workspace/invariants.riido.json
  docs/20-domain/workspace/invariants/scope.md
  docs/20-domain/workspace/invariants/scope.riido.json
  docs/20-domain/workspace/invariants/core.md
  docs/20-domain/workspace/invariants/core.riido.json
  docs/20-domain/workspace/invariants/lifecycle.md
  docs/20-domain/workspace/invariants/lifecycle.riido.json
  docs/20-domain/workspace/invariants/operations.md
  docs/20-domain/workspace/invariants/operations.riido.json
  docs/20-domain/workspace/invariants/directory-layout.md
  docs/20-domain/workspace/invariants/directory-layout.riido.json
  docs/20-domain/workspace/invariants/store-channel-grants.md
  docs/20-domain/workspace/invariants/store-channel-grants.riido.json
  docs/20-domain/workspace/invariants/local-archive-manifest.md
  docs/20-domain/workspace/invariants/local-archive-manifest.riido.json
  docs/20-domain/workspace/invariants/repo-cache-isolation.md
  docs/20-domain/workspace/invariants/repo-cache-isolation.riido.json
  docs/20-domain/workspace/invariants/native-config-injection.md
  docs/20-domain/workspace/invariants/native-config-injection.riido.json
  .github/workflows/workspace-invariants-docs.yml
  docs/20-domain/workspace/native-config-manifest.md
  docs/20-domain/workspace/native-config-manifest.riido.json
  docs/20-domain/workspace/native-config-manifest/manifest-materialization.md
  docs/20-domain/workspace/native-config-manifest/manifest-materialization.riido.json
  docs/20-domain/workspace/native-config-manifest/overlay-and-hooks.md
  docs/20-domain/workspace/native-config-manifest/overlay-and-hooks.riido.json
  docs/20-domain/workspace/native-config-manifest/native-config-version.md
  docs/20-domain/workspace/native-config-manifest/native-config-version.riido.json
  docs/20-domain/workspace/native-config-manifest/workspace-lock-policy.md
  docs/20-domain/workspace/native-config-manifest/workspace-lock-policy.riido.json
  docs/20-domain/workspace/native-config-manifest/adjacent-contracts.md
  docs/20-domain/workspace/native-config-manifest/adjacent-contracts.riido.json
  docs/20-domain/workspace/native-config-manifest/resolved-decisions.md
  docs/20-domain/workspace/native-config-manifest/resolved-decisions.riido.json
  .github/workflows/workspace-native-config-docs.yml
  docs/20-domain/distribution-host-integration.md
  docs/20-domain/distribution-host-integration.riido.json
  docs/20-domain/distribution-host-integration/store-channel-policy.md
  docs/20-domain/distribution-host-integration/store-channel-policy.riido.json
  docs/20-domain/distribution-host-integration/store-channel-policy/review-demo-mode.md
  docs/20-domain/distribution-host-integration/store-channel-policy/review-demo-mode.riido.json
  docs/20-domain/distribution-host-integration/store-channel-policy/open-questions.md
  docs/20-domain/distribution-host-integration/store-channel-policy/open-questions.riido.json
  docs/20-domain/distribution-host-integration/store-channel-policy/versioning.md
  docs/20-domain/distribution-host-integration/store-channel-policy/versioning.riido.json
  .github/workflows/distribution-host-docs.yml
  docs/20-domain/distribution-host-integration/invariants.md
  docs/20-domain/distribution-host-integration/invariants.riido.json
  docs/20-domain/distribution-host-integration/invariants/core.md
  docs/20-domain/distribution-host-integration/invariants/core.riido.json
  docs/20-domain/distribution-host-integration/invariants/channels-and-roles.md
  docs/20-domain/distribution-host-integration/invariants/channels-and-roles.riido.json
  docs/20-domain/distribution-host-integration/invariants/external-tool-registry.md
  docs/20-domain/distribution-host-integration/invariants/external-tool-registry.riido.json
  docs/20-domain/distribution-host-integration/invariants/app-data-root.md
  docs/20-domain/distribution-host-integration/invariants/app-data-root.riido.json
  docs/20-domain/distribution-host-integration/invariants/workspace-grant-store.md
  docs/20-domain/distribution-host-integration/invariants/workspace-grant-store.riido.json
  .github/workflows/distribution-host-invariants-docs.yml
  docs/20-domain/distribution-host-integration/local-ipc.md
  docs/20-domain/distribution-host-integration/local-ipc.riido.json
  docs/20-domain/distribution-host-integration/local-ipc/endpoint-model.md
  docs/20-domain/distribution-host-integration/local-ipc/endpoint-model.riido.json
  docs/20-domain/distribution-host-integration/local-ipc/macos-helper-strategy.md
  docs/20-domain/distribution-host-integration/local-ipc/macos-helper-strategy.riido.json
  docs/20-domain/distribution-host-integration/local-ipc/macos-external-provider-cli.md
  docs/20-domain/distribution-host-integration/local-ipc/macos-external-provider-cli.riido.json
  docs/20-domain/distribution-host-integration/local-ipc/windows-msix-strategy.md
  docs/20-domain/distribution-host-integration/local-ipc/windows-msix-strategy.riido.json
  docs/20-domain/distribution-host-integration/local-ipc/consent-ledger.md
  docs/20-domain/distribution-host-integration/local-ipc/consent-ledger.riido.json
  .github/workflows/distribution-host-local-ipc-docs.yml
  docs/README.md
  docs/executable-knowledge.md
  docs/executable-knowledge.riido.json
  docs/readme/document-map.md
  docs/readme/document-map.riido.json
  docs/readme/verification.md
  docs/readme/verification.riido.json
  docs/20-domain/distribution-host-integration/store-channel-policy/policy-table.md
  docs/20-domain/distribution-host-integration/store-channel-policy/policy-table.riido.json
  docs/20-domain/distribution-host-integration/store-channel-policy/server-facing-metadata.md
  docs/20-domain/distribution-host-integration/store-channel-policy/server-facing-metadata.riido.json
  docs/20-domain/provider-runtime/adapter-acl/event-ingestor-contract.md
  docs/20-domain/provider-runtime/adapter-acl/event-ingestor-contract.riido.json
  docs/20-domain/provider-runtime/runtime-responsibility/provider-event-draft.md
  docs/20-domain/provider-runtime/runtime-responsibility/provider-event-draft.riido.json
  docs/20-domain/provider-runtime/public-migration-status.md
  docs/20-domain/provider-runtime/public-migration-status.riido.json
  docs/20-domain/provider-runtime/public-migration-status/scope-boundaries.md
  docs/20-domain/provider-runtime/public-migration-status/core-packages.md
  docs/20-domain/provider-runtime/public-migration-status/claude.md
  docs/20-domain/provider-runtime/public-migration-status/codex.md
  docs/20-domain/provider-runtime/public-migration-status/openclaw.md
  docs/20-domain/provider-runtime/public-migration-status/cursor.md
  .github/workflows/provider-public-migration-docs.yml
  docs/20-domain/security/enforcement-locations/native-config-and-mcp.md
  docs/20-domain/security/enforcement-locations/native-config-and-mcp.riido.json
  docs/20-domain/security/enforcement-locations/tool-use-gates.md
  docs/20-domain/security/enforcement-locations/tool-use-gates.riido.json
  docs/20-domain/security/enforcement-locations/unsafe-bypass.md
  docs/20-domain/security/enforcement-locations/unsafe-bypass.riido.json
  docs/20-domain/security/invariants/policy-bundle-loader.md
  docs/20-domain/security/invariants/policy-bundle-loader.riido.json
  docs/20-domain/security/native-config-overlay/full-access-runtime-harness.md
  docs/20-domain/security/native-config-overlay/full-access-runtime-harness.riido.json
  docs/20-domain/validation.md
  docs/20-domain/validation.riido.json
  docs/20-domain/runtime-scheduling.md
  docs/20-domain/runtime-scheduling.riido.json
  docs/20-domain/runtime-scheduling/saas-assignment-source.md
  docs/20-domain/runtime-scheduling/saas-assignment-source.riido.json
  docs/20-domain/runtime-scheduling/invariants.md
  docs/20-domain/runtime-scheduling/invariants/core.md
  docs/20-domain/runtime-scheduling/invariants/core.riido.json
  docs/20-domain/runtime-scheduling/invariants/local-daemon-contract.md
  docs/20-domain/runtime-scheduling/invariants/local-daemon-contract.riido.json
  docs/20-domain/runtime-scheduling/invariants/runtime-eligibility.md
  docs/20-domain/runtime-scheduling/invariants/runtime-eligibility.riido.json
  docs/20-domain/runtime-scheduling/invariants/task-requirements.md
  docs/20-domain/runtime-scheduling/invariants/task-requirements.riido.json
  docs/30-architecture/module-decomposition.md
  docs/30-architecture/module-decomposition.riido.json
  docs/30-architecture/module-decomposition/import-rules.riido.json
  docs/30-architecture/module-decomposition/package-roles.riido.json
  docs/30-architecture/module-decomposition/ports.riido.json
  docs/30-architecture/module-decomposition/12-factor-boundary.md
  docs/30-architecture/module-decomposition/change-procedure.md
  docs/30-architecture/module-decomposition/hexagonal-ports.md
  docs/30-architecture/module-decomposition/import-rules.md
  docs/30-architecture/module-decomposition/package-map.md
  .github/workflows/module-decomposition-docs.yml
  docs/30-architecture/store-distribution.riido.json
  .github/workflows/store-distribution-docs.yml
  docs/30-architecture/agent-execution-unresolved-design.riido.json
  docs/30-architecture/agent-execution-unresolved-design/execution-model.riido.json
  docs/30-architecture/agent-execution-unresolved-design/governance.riido.json
  docs/30-architecture/agent-execution-unresolved-design/lifecycle-model.riido.json
  docs/30-architecture/agent-execution-unresolved-design/overview.riido.json
  docs/30-architecture/agent-execution-unresolved-design/risk-model.riido.json
  .github/workflows/agent-execution-design-docs.yml
  docs/30-architecture/cli-surface.md
  docs/30-architecture/cli-surface.riido.json
  docs/30-architecture/config-reference.md
  docs/30-architecture/config-reference.riido.json
  docs/30-architecture/config-reference/executable-search-path.md
  docs/30-architecture/config-reference/executable-search-path.riido.json
  docs/30-architecture/executable-knowledge.md
  docs/30-architecture/executable-knowledge.riido.json
  .github/workflows/repo-executable-knowledge-coverage.yml
  docs/30-architecture/release-artifacts.md
  docs/30-architecture/release-artifacts.riido.json
  docs/30-architecture/release-artifacts/assets.md
  docs/30-architecture/release-artifacts/desktop-msix-cdn.md
  docs/30-architecture/release-artifacts/installer.md
  docs/30-architecture/release-artifacts/review-boundary.md
  .github/workflows/release-artifact-docs.yml
  docs/30-architecture/integration-matrix.md
  docs/30-architecture/integration-matrix.riido.json
  docs/30-architecture/integration-matrix/assertions.md
  docs/30-architecture/integration-matrix/change-procedure.md
  docs/30-architecture/integration-matrix/gate-policy.md
  docs/30-architecture/integration-matrix/instruction-effectiveness.md
  docs/30-architecture/integration-matrix/provider-matrix.md
  .github/workflows/integration-matrix-docs.yml
  docs/30-architecture/compatibility-gate.md
  docs/30-architecture/compatibility-gate.riido.json
  docs/30-architecture/runtime-upgrade-flow.md
  docs/30-architecture/runtime-upgrade-flow.riido.json
  docs/30-architecture/loop-engineering.md
  docs/30-architecture/loop-engineering.riido.json
  .github/workflows/loop-engineering-evidence.yml
  docs/30-architecture/loop-engineering/context-map-docs.riido.json
  docs/30-architecture/loop-engineering/provider-public-migration-docs.riido.json
  docs/30-architecture/loop-engineering/locking-docs.riido.json
  docs/30-architecture/loop-engineering/security-docs.riido.json
  docs/30-architecture/loop-engineering/security-redaction.riido.json
  docs/30-architecture/loop-engineering/security-invariants-docs.riido.json
  docs/30-architecture/loop-engineering/security-native-config-overlay-docs.riido.json
  docs/30-architecture/loop-engineering/provider-runtime-responsibility-docs.riido.json
  docs/30-architecture/loop-engineering/provider-adapter-acl-docs.riido.json
  docs/30-architecture/loop-engineering/provider-integration-gate-docs.riido.json
  docs/30-architecture/loop-engineering/provider-runtime-boundary-docs.riido.json
  docs/30-architecture/loop-engineering/workspace-docs.riido.json
  docs/30-architecture/loop-engineering/workspace-invariants-docs.riido.json
  docs/30-architecture/loop-engineering/workspace-native-config-docs.riido.json
  docs/30-architecture/loop-engineering/distribution-host-docs.riido.json
  docs/30-architecture/loop-engineering/distribution-host-invariants-docs.riido.json
  docs/30-architecture/loop-engineering/distribution-host-local-ipc-docs.riido.json
  docs/30-architecture/loop-engineering/cli-surface-evidence.riido.json
  docs/30-architecture/loop-engineering/config-reference-evidence.riido.json
  docs/30-architecture/loop-engineering/executable-search-path-evidence.riido.json
  docs/30-architecture/loop-engineering/repo-executable-knowledge-coverage.riido.json
  docs/30-architecture/loop-engineering/loop-evidence-output.riido.json
  docs/30-architecture/loop-engineering/knowledge-coverage-breakdown.riido.json
  docs/30-architecture/loop-engineering/release-artifact-docs.riido.json
  docs/30-architecture/loop-engineering/integration-matrix-docs.riido.json
  docs/30-architecture/loop-engineering/module-decomposition-docs.riido.json
  docs/30-architecture/loop-engineering/store-distribution-docs.riido.json
  docs/30-architecture/loop-engineering/agent-execution-design-docs.riido.json
  docs/30-architecture/loop-engineering/runtime-scheduling-docs.riido.json
  docs/30-architecture/loop-engineering/saas-assignment-source.riido.json
  docs/30-architecture/loop-engineering/local-daemon-contract-evidence.riido.json
  docs/30-architecture/loop-engineering/runtime-eligibility-evidence.riido.json
  docs/30-architecture/loop-engineering/task-requirements-evidence.riido.json
  docs/30-architecture/loop-engineering/tool-use-gate-evidence.riido.json
  docs/30-architecture/loop-engineering/native-config-mcp-evidence.riido.json
  docs/30-architecture/loop-engineering/full-access-harness-evidence.riido.json
  docs/30-architecture/loop-engineering/privacy-metadata-evidence.riido.json
  docs/30-architecture/loop-engineering/unsafe-bypass-evidence.riido.json
  docs/30-architecture/provider-real-cli-observation.md
  docs/30-architecture/provider-real-cli-observation.riido.json
  docs/30-architecture/runtime-secret-private-evidence.md
  docs/30-architecture/runtime-secret-private-evidence.riido.json
  docs/20-domain/provider-runtime/adapter-draft-fields/idle-watchdog.md
  docs/20-domain/provider-runtime/adapter-draft-fields/idle-watchdog.riido.json
  docs/20-domain/provider-runtime/adapter-draft-fields/run-lifecycle.riido.json
  docs/20-domain/provider-runtime/adapter-draft-fields/cancel-interrupt-input.riido.json
  docs/20-domain/provider-runtime/adapter-draft-fields/approval-wait-timeout.riido.json
  docs/20-domain/provider-runtime/adapter-draft-fields/process-lifecycle.riido.json
  docs/20-domain/provider-runtime/adapter-draft-fields/draft-field-surface.riido.json
  docs/20-domain/provider-runtime/adapter-draft-fields/session-lifecycle.riido.json
  docs/30-architecture/figma-ai-agent-daemon-boundary.md
  docs/30-architecture/figma-ai-agent-daemon-boundary.riido.json
  .github/workflows/figma-boundary-docs.yml
  docs/30-architecture/agent-execution-unresolved-design/assignment-lifecycle-fsm.md
  docs/30-architecture/agent-execution-unresolved-design/assignment-lifecycle-fsm.riido.json
  docs/30-architecture/agent-execution-unresolved-design/assignment-lifecycle-evidence.riido.json
  docs/30-architecture/loop-engineering/assignment-fsm-evidence.riido.json
  docs/30-architecture/riido-work-branch-gate.md
  docs/30-architecture/riido-work-branch-gate.riido.json
  docs/migration/daemon/riidoapi-local-api/4689-saasplane-assignment-polling.md
  docs/50-roadmap/open-questions.md
  .github/workflows/runtime-scheduling-docs.yml
  .github/workflows/policy-bundle-loader-evidence.yml
  .github/workflows/local-daemon-contract-evidence.yml
  .github/workflows/runtime-eligibility-evidence.yml
  .github/workflows/task-requirements-evidence.yml
  .github/workflows/tool-use-gate-evidence.yml
  .github/workflows/native-config-mcp-evidence.yml
  .github/workflows/full-access-harness-evidence.yml
  .github/workflows/assignment-fsm-evidence.yml
  .github/workflows/privacy-metadata-evidence.yml
  .github/workflows/store-distribution-contract.yml
  .github/workflows/cli-surface-evidence.yml
  .github/workflows/config-reference-evidence.yml
  .github/workflows/executable-search-path-evidence.yml
  .github/workflows/executable-knowledge-coverage.yml
  .github/workflows/unsafe-bypass-evidence.yml
  .github/workflows/saas-assignment-source.yml
  .github/workflows/validation-evidence.yml
)

for path in "${required_files[@]}"; do
  test -f "$path"
done
