package main

import (
	"bytes"
	"fmt"
)

func render(manifest Manifest) string {
	var b bytes.Buffer
	fmt.Fprintf(&b, "# %s\n\n", manifest.Title)
	b.WriteString("<!-- Generated by go run ./tools/terminalresultmapping -write-doc. Do not edit by hand. -->\n\n")
	b.WriteString("[Back to adapter-draft-fields.md](../adapter-draft-fields.md)\n\n")
	b.WriteString("Executable SSOT: [`run-lifecycle.riido.json`](run-lifecycle.riido.json).\n\n")
	fmt.Fprintf(&b, "Evidence artifact: `%s`.\n\n", manifest.EvidenceArtifact)
	b.WriteString("## Terminal Result Mapping\n\n")
	b.WriteString("| ResultStatus | EventType |\n| --- | --- |\n")
	for _, row := range manifest.Mappings {
		fmt.Fprintf(&b, "| `%s` | `%s` |\n", row.Status, row.EventType)
	}
	writeDefaults(&b, manifest.Defaults)
	writeLifecycle(&b)
	writeAssertions(&b, manifest.Assertions)
	return b.String()
}

func writeDefaults(b *bytes.Buffer, defaults Defaults) {
	b.WriteString("\n## Defaults\n\n")
	fmt.Fprintf(b, "- Empty status normalizes to `%s`.\n", defaults.EmptyStatusConst)
	fmt.Fprintf(b, "- Unknown terminal statuses fall back to `%s`.\n", defaults.FallbackEventType)
}
