package main

import (
	"bytes"
	"fmt"
)

func render(manifest Manifest) string {
	var b bytes.Buffer
	fmt.Fprintf(&b, "# %s\n\n", manifest.Title)
	b.WriteString("<!-- Generated by go run ./tools/shutdownauthority -write-doc. Do not edit by hand. -->\n\n")
	b.WriteString("[Back to adapter-draft-fields.md](../adapter-draft-fields.md)\n\n")
	b.WriteString("Executable SSOT: [`cancel-interrupt-input.riido.json`](cancel-interrupt-input.riido.json).\n\n")
	fmt.Fprintf(&b, "Evidence artifact: `%s`.\n\n", manifest.EvidenceArtifact)
	writeSignals(&b, manifest.ExternalSignals)
	writeLevels(&b, manifest.Levels, manifest.Timeouts)
	writeAssertions(&b, manifest.Assertions)
	return b.String()
}

func writeSignals(b *bytes.Buffer, rows []ExternalSignal) {
	b.WriteString("## External Signals\n\n| External signal | Adapter action |\n| --- | --- |\n")
	for _, row := range rows {
		fmt.Fprintf(b, "| %s | %s |\n", row.Signal, row.Action)
	}
}
