package main

import (
	"bytes"
	"fmt"
)

func render(manifest Manifest) string {
	var b bytes.Buffer
	fmt.Fprintf(&b, "# %s\n\n", manifest.Title)
	b.WriteString("<!-- Generated by go run ./tools/runtimeupgrade -write-doc. Do not edit by hand. -->\n\n")
	b.WriteString("Executable SSOT: [`runtime-upgrade-flow.riido.json`](runtime-upgrade-flow.riido.json).\n\n")
	fmt.Fprintf(&b, "Evidence artifact: `%s`.\n\n", manifest.EvidenceArtifact)
	fmt.Fprintf(&b, "Invariant: %s\n\n", manifest.Invariant)
	writeRuleTable(&b, "Versioned Inputs", manifest.Inputs)
	writeRuleTable(&b, "Flow", manifest.Flow)
	writeRuleTable(&b, "Policy", manifest.Policies)
	writeRuleTable(&b, "Native Config", manifest.NativeConfig)
	writeAbsentSurfaces(&b, manifest.AbsentSurfaces)
	writeAssertions(&b, manifest.Assertions)
	return b.String()
}

func writeRuleTable(b *bytes.Buffer, title string, rules []Rule) {
	b.WriteString("## " + title + "\n\n")
	b.WriteString("| Item | Status | Decisions | Summary / Owner | Evidence |\n| --- | --- | --- | --- | --- |\n")
	for _, rule := range rules {
		fmt.Fprintf(
			b, "| %s | `%s` | %s | %s | %s |\n",
			ruleLabel(rule), rule.Status, ruleDecisions(rule), ruleSummary(rule), ruleEvidence(rule),
		)
	}
	b.WriteString("\n")
}
