package main

import (
	"bytes"
	"fmt"
)

func render(manifest Manifest) string {
	var b bytes.Buffer
	fmt.Fprintf(&b, "# %s\n\n", manifest.Title)
	b.WriteString("<!-- Generated by go run ./tools/providerdraftmapping -write-doc. Do not edit by hand. -->\n\n")
	b.WriteString("Executable SSOT: [`provider-event-draft.riido.json`](provider-event-draft.riido.json).\n\n")
	fmt.Fprintf(&b, "Evidence artifact: `%s`.\n\n", manifest.EvidenceArtifact)
	b.WriteString("ProviderEventDraft is the only domain output an adapter may produce.\n\n")
	b.WriteString("## Mapped Events\n\n| EventKind | EventType |\n| --- | --- |\n")
	for _, row := range manifest.MappedEvents {
		fmt.Fprintf(&b, "| `%s` | `%s` |\n", row.EventKind, row.EventType)
	}
	b.WriteString("\n## Skipped Events\n\n| EventKind | Reason |\n| --- | --- |\n")
	for _, row := range manifest.SkippedEvents {
		fmt.Fprintf(&b, "| `%s` | %s |\n", row.EventKind, row.Reason)
	}
	writeAssertions(&b, manifest.Assertions)
	return b.String()
}

func writeAssertions(b *bytes.Buffer, assertions []string) {
	b.WriteString("\n## Assertions\n\n")
	for _, assertion := range assertions {
		fmt.Fprintf(b, "- `%s`\n", assertion)
	}
}
