package main

import (
	"fmt"
	"strings"
)

func renderMarkdown(m Manifest) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# %s\n\n", m.Title)
	b.WriteString("<!-- Generated by go run ./tools/executablesearchpath -write-doc. Do not edit by hand. -->\n\n")
	b.WriteString("[Back to Daemon Config Reference](../config-reference.md)\n\n")
	b.WriteString("Executable SSOT: [`executable-search-path.riido.json`](executable-search-path.riido.json).\n\n")
	fmt.Fprintf(&b, "Evidence artifact: `%s`.\n\n", m.EvidenceArtifact)
	fmt.Fprintf(&b, "%s\n\n", m.Purpose)
	renderSearchOrder(&b, m.SearchOrder)
	renderRules(&b, m.Rules)
	renderAssertions(&b, m.Assertions)
	return b.String()
}

func renderSearchOrder(b *strings.Builder, rows []SearchStep) {
	b.WriteString("## Search Order\n\n")
	b.WriteString("| Order | Source | Meaning | Evidence |\n| --- | --- | --- | --- |\n")
	for _, row := range rows {
		fmt.Fprintf(b, "| %d | %s | %s | %s |\n",
			row.Order, row.Name, row.Summary, checks(row.SourceChecks))
	}
	b.WriteByte('\n')
}

func checks(names []string) string {
	return "`" + strings.Join(names, "`, `") + "`"
}
