package main

import (
	"os"
	"path/filepath"
	"strings"
)

func countFiles(root, pattern string) int {
	matches, _ := filepath.Glob(filepath.Join(root, pattern))
	if !strings.Contains(pattern, "**") {
		return len(matches)
	}
	count := 0
	_ = filepath.WalkDir(root, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			return nil
		}
		if ok, _ := filepath.Match("*_test.go", filepath.Base(path)); ok {
			count++
		}
		return nil
	})
	return count
}

func countGeneratedDocs(root string) int {
	count := 0
	_ = filepath.WalkDir(filepath.Join(root, "docs"), func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() || filepath.Ext(path) != ".md" {
			return nil
		}
		data, err := os.ReadFile(path)
		if err == nil && strings.Contains(string(data), "Generated by") {
			count++
		}
		return nil
	})
	return count
}

func ratio(value, total int) float64 {
	if total == 0 {
		return 0
	}
	return float64(value) / float64(total)
}
