package main

import (
	"fmt"
	"strings"
)

func renderDoc(m manifest) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# %s\n\n", m.Title)
	b.WriteString("<!-- Generated by go run ./tools/productloopevidence -write-doc. Do not edit by hand. -->\n\n")
	fmt.Fprintf(&b, "- SSOT: `%s`\n", defaultManifest)
	fmt.Fprintf(&b, "- Workflow: `%s`\n", m.Workflow)
	fmt.Fprintf(&b, "- Evidence artifact: `%s`\n\n", m.EvidenceArtifact)
	renderLoop(&b, m.Loop)
	renderSignals(&b, m.OutcomeSignals)
	renderThresholds(&b, m.Thresholds)
	return strings.TrimRight(b.String(), "\n") + "\n"
}

func renderLoop(b *strings.Builder, loop evidenceLoop) {
	b.WriteString("## Loop\n\n")
	fmt.Fprintf(b, "- Observation: %s\n", loop.Observation)
	fmt.Fprintf(b, "- Hypothesis: %s\n", loop.Hypothesis)
	fmt.Fprintf(b, "- Execute: %s\n", loop.Execute)
	fmt.Fprintf(b, "- Evaluate: %s\n", loop.Evaluate)
	fmt.Fprintf(b, "- Retrospective: %s\n\n", loop.Retrospective)
}

func renderSignals(b *strings.Builder, signals []outcomeSignal) {
	b.WriteString("## Product Outcome Signals\n\n")
	b.WriteString("| Signal | Scenario bindings |\n| --- | --- |\n")
	for _, signal := range signals {
		fmt.Fprintf(b, "| `%s` | `%s` |\n", signal.ID, strings.Join(signal.ScenarioIDs, "`, `"))
	}
	b.WriteString("\n")
}

func renderThresholds(b *strings.Builder, t thresholds) {
	b.WriteString("## Partial Thresholds\n\n")
	fmt.Fprintf(b, "- Max entrypoints before partial: `%d`\n", t.MaxEntrypointsBeforePartial)
	fmt.Fprintf(b, "- Stale partial after days: `%d`\n", t.StalePartialAfterDays)
}
