package main

import (
	"fmt"
	"strings"
)

func renderRouteDoc(routes entrypointRouteMap, source string) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# %s\n\n", routes.Title)
	b.WriteString("<!-- Generated by go run ./tools/productloopevidence -write-doc. Do not edit by hand. -->\n\n")
	fmt.Fprintf(&b, "- SSOT: `%s`\n", source)
	fmt.Fprintf(&b, "- Schema: `%s`\n\n", routes.SchemaVersion)
	renderLoop(&b, routes.Loop)
	b.WriteString("## Routes\n\n")
	b.WriteString("| Route | Owner | Entrypoint globs |\n| --- | --- | --- |\n")
	for _, route := range routes.Routes {
		fmt.Fprintf(&b, "| `%s` | `%s` | `%s` |\n", route.ID, route.Owner, strings.Join(route.Includes, "`, `"))
	}
	return strings.TrimRight(b.String(), "\n") + "\n"
}
