package main

import (
	"bytes"
	"fmt"
	"strings"
)

func renderedDocs(manifest Manifest) map[string]string {
	return map[string]string{
		manifest.GeneratedDoc: renderDomainDoc(manifest),
		manifest.MigrationDoc: renderMigrationDoc(manifest),
	}
}

func renderDomainDoc(m Manifest) string {
	var b bytes.Buffer
	fmt.Fprintf(&b, "# %s\n\n", m.Title)
	b.WriteString("<!-- Generated by go run ./tools/saasassignment -write-doc. Do not edit by hand. -->\n\n")
	b.WriteString("[Back to runtime-scheduling.md](../runtime-scheduling.md)\n\n")
	b.WriteString("Executable SSOT: [`saas-assignment-source.riido.json`](saas-assignment-source.riido.json).\n\n")
	fmt.Fprintf(&b, "Evidence artifact: `%s`.\n\n%s\n\n", m.EvidenceArtifact, m.Purpose)
	writeFactTable(&b, m.Facts)
	writeBoundaryTable(&b, m.Boundaries)
	writeAbsentTable(&b, m.AbsentSurfaces)
	writeAssertions(&b, m.Assertions)
	return b.String()
}

func renderMigrationDoc(m Manifest) string {
	var b bytes.Buffer
	b.WriteString("# RIID-4689 — saasplane Assignment Polling Adapter Migration\n\n")
	b.WriteString("<!-- Generated by go run ./tools/saasassignment -write-doc. Do not edit by hand. -->\n\n")
	b.WriteString("[Back to riidoapi local API](../riidoapi-local-api.md)\n\n")
	fmt.Fprintf(&b, "Executable SSOT: [`%s`](../../../20-domain/runtime-scheduling/saas-assignment-source.riido.json).\n\n", m.ID)
	fmt.Fprintf(&b, "Canonical generated reader doc: [`%s`](../../../20-domain/runtime-scheduling/saas-assignment-source.md).\n\n", m.Title)
	b.WriteString("This migration slice is verified by `saas-assignment-source-evidence`; implementation and boundary claims live in the generated runtime scheduling document.\n")
	return b.String()
}

func writeAssertions(b *bytes.Buffer, assertions []string) {
	b.WriteString("## Assertions\n\n")
	for _, assertion := range assertions {
		fmt.Fprintf(b, "- `%s`\n", assertion)
	}
}

func checksList(checks []string) string {
	if len(checks) == 0 {
		return ""
	}
	return "`" + strings.Join(checks, "`, `") + "`"
}
