package main

import (
	"fmt"
	"strings"
)

func renderMarkdown(manifest Manifest) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# %s\n\n", manifest.Title)
	fmt.Fprintln(&b, "<!-- Generated by go run ./tools/fullaccessharness -write-doc. Do not edit by hand. -->")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "[Back to native-config-overlay](../native-config-overlay.md)")
	fmt.Fprintln(&b)
	fmt.Fprintf(&b, "Executable SSOT: [`%s`](full-access-runtime-harness.riido.json).\n\n", manifestID(manifest))
	fmt.Fprintf(&b, "Evidence artifact: `%s`.\n\n", manifest.EvidenceArtifact)
	fmt.Fprintf(&b, "%s\n\n", manifest.Purpose)
	renderFacts(&b, manifest)
	renderAbsent(&b, manifest)
	renderAssertions(&b, manifest)
	return b.String()
}

func manifestID(manifest Manifest) string {
	if manifest.ID == "" {
		return "full-access-runtime-harness.riido.json"
	}
	return "full-access-runtime-harness.riido.json"
}
