package main

import (
	"bytes"
	"fmt"
)

func renderForbidden(manifest Manifest) string {
	var b bytes.Buffer
	fmt.Fprintf(&b, "# Forbidden Draft Fields\n\n")
	b.WriteString("<!-- Generated by go run ./tools/draftfields -write-doc. Do not edit by hand. -->\n\n")
	b.WriteString("[Back to adapter-draft-fields.md](../adapter-draft-fields.md)\n\n")
	b.WriteString("Executable SSOT: [`draft-field-surface.riido.json`](draft-field-surface.riido.json).\n\n")
	fmt.Fprintf(&b, "Evidence artifact: `%s`.\n\n", manifest.EvidenceArtifact)
	b.WriteString("## Authority Boundary\n\n")
	b.WriteString("Adapter observes. Adapter ACL creates a normalized draft. Only EventIngestor appends.\n\n")
	b.WriteString("## Fields\n\n| Field | Filled by | Why not adapter |\n| --- | --- | --- |\n")
	for _, field := range manifest.ForbiddenFields {
		fmt.Fprintf(&b, "| `%s` | %s | %s |\n", field.Field, field.FilledBy, field.Reason)
	}
	writeAssertions(&b, manifest.Assertions)
	return b.String()
}
