package main

import (
	"bytes"
	"fmt"
)

func renderAllowed(manifest Manifest) string {
	var b bytes.Buffer
	fmt.Fprintf(&b, "# Allowed Draft Fields\n\n")
	b.WriteString("<!-- Generated by go run ./tools/draftfields -write-doc. Do not edit by hand. -->\n\n")
	b.WriteString("[Back to adapter-draft-fields.md](../adapter-draft-fields.md)\n\n")
	b.WriteString("Executable SSOT: [`draft-field-surface.riido.json`](draft-field-surface.riido.json).\n\n")
	fmt.Fprintf(&b, "Evidence artifact: `%s`.\n\n", manifest.EvidenceArtifact)
	b.WriteString("## Fields\n\n| Field | Status | Meaning |\n| --- | --- | --- |\n")
	for _, field := range manifest.AllowedFields {
		fmt.Fprintf(&b, "| `%s` | `%s` | %s |\n", field.Field, field.Status, field.Meaning)
	}
	b.WriteString("\n## Status Meaning\n\n")
	b.WriteString("- `implemented`: emitted by current draft construction code.\n")
	b.WriteString("- `source_only`: present before draft construction but not currently emitted.\n")
	b.WriteString("- `reserved`: vocabulary allowed for future use but not claimed as emitted.\n")
	return b.String()
}
