package main

import (
	"fmt"
	"strings"
)

func renderReadme(m manifest) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# %s\n\n", m.Title)
	b.WriteString("<!-- Generated by go run ./tools/docmap -write. Do not edit by hand. -->\n\n")
	b.WriteString("Executable SSOT: [`docs/readme/document-map.riido.json`](readme/document-map.riido.json).\n\n")
	fmt.Fprintf(&b, "%s\n\n", m.Intro)
	renderReadOrder(&b, m.GeneratedDocs.Readme, m.ReadOrder)
	renderDecisions(&b, m.GeneratedDocs.Readme, m.Decisions)
	renderRepos(&b, m.Repos)
	renderRules(&b, m.Rules)
	return b.String()
}

func renderDocumentMap(m manifest) string {
	var b strings.Builder
	b.WriteString("# README: Document Map\n\n")
	b.WriteString("<!-- Generated by go run ./tools/docmap -write. Do not edit by hand. -->\n\n")
	b.WriteString("[Back to README](../README.md)\n\n")
	b.WriteString("Executable SSOT: [`document-map.riido.json`](document-map.riido.json).\n\n")
	renderDecisions(&b, m.GeneratedDocs.DocumentMap, m.Decisions)
	return b.String()
}

func renderReadOrder(b *strings.Builder, docPath string, rows []readEntry) {
	b.WriteString("## 읽는 순서\n\n")
	for i, row := range rows {
		fmt.Fprintf(b, "%d. [`%s`](%s): %s\n",
			i+1, linkLabel(row.Doc), linkFrom(docPath, row.Doc), row.Description)
	}
	b.WriteByte('\n')
}

func renderDecisions(b *strings.Builder, docPath string, rows []decision) {
	b.WriteString("## 결정별 문서\n\n| 결정 | SSOT |\n| --- | --- |\n")
	for _, row := range rows {
		fmt.Fprintf(b, "| %s | %s |\n", row.Topic, renderLinks(docPath, row.Docs))
	}
	b.WriteByte('\n')
}
