package main

import (
	"fmt"
	"strings"
)

const generatedHeader = "<!-- Generated by go run ./tools/roadmapdocs -write-doc. Do not edit by hand. -->"

func renderDoc(m manifest) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# %s\n\n%s\n\n", m.Title, generatedHeader)
	if m.RiidoTask != "" {
		fmt.Fprintf(&b, "> Riido task: %s\n\n", m.RiidoTask)
	}
	for _, paragraph := range m.Intro {
		fmt.Fprintf(&b, "%s\n\n", paragraph)
	}
	writeQuestionTable(&b, m.Questions)
	if m.PromotionRule != "" {
		fmt.Fprintf(&b, "\n%s\n", m.PromotionRule)
	}
	return strings.TrimRight(b.String(), "\n") + "\n"
}

func writeQuestionTable(b *strings.Builder, questions []question) {
	b.WriteString("| ID | Area | Question | Current handling |\n")
	b.WriteString("| --- | --- | --- | --- |\n")
	for _, q := range questions {
		fmt.Fprintf(
			b,
			"| %s | %s | %s | %s |\n",
			q.ID,
			q.Area,
			q.Question,
			q.CurrentHandling,
		)
	}
}
