package main

import (
	"fmt"
	"strings"
)

func renderDetailDoc(manifest Manifest, doc DetailDoc) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# %s\n\n", doc.Title)
	b.WriteString("<!-- Generated by go run ./tools/clisurface -write-doc. Do not edit by hand. -->\n\n")
	b.WriteString("[Back to CLI Surface SSOT](../cli-surface.md)\n\n")
	for _, block := range doc.Blocks {
		renderDetailBlock(&b, manifest, block)
	}
	return strings.TrimRight(b.String(), "\n") + "\n"
}

func renderDetailBlock(b *strings.Builder, manifest Manifest, block DetailBlock) {
	switch block.Kind {
	case "paragraph":
		fmt.Fprintf(b, "%s\n\n", block.Text)
	case "bullets":
		renderDetailBullets(b, block.Items)
	case "commands":
		renderCommandFence(b, block.Items)
	case "command_groups_table":
		renderSimpleCommandGroups(b, manifest.CommandGroups)
	}
}
