package main

import (
	"fmt"
	"strings"
)

func renderMarkdown(manifest Manifest) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# %s\n\n", manifest.Title)
	b.WriteString("<!-- Generated by go run ./tools/clisurface -write-doc. Do not edit by hand. -->\n\n")
	b.WriteString("Executable SSOT: [`cli-surface.riido.json`](cli-surface.riido.json).\n\n")
	fmt.Fprintf(&b, "Evidence artifact: `%s`.\n\n", manifest.EvidenceArtifact)
	fmt.Fprintf(&b, "%s\n\n", manifest.Purpose)
	renderCommandGroups(&b, manifest.CommandGroups)
	renderProviders(&b, manifest.Providers)
	renderRelated(&b, manifest.RelatedSections)
	renderAssertions(&b, manifest.Assertions)
	return b.String()
}

func renderCommandGroups(b *strings.Builder, groups []CommandGroup) {
	b.WriteString("## Command Groups\n\n")
	b.WriteString("| Group | Subcommands | Owner | Boundary | Evidence |\n| --- | --- | --- | --- | --- |\n")
	for _, group := range groups {
		fmt.Fprintf(b, "| `%s` | %s | %s | %s | %s |\n",
			group.Name, codeList(group.Subcommands), group.Owner, group.Boundary, codeList(group.SourceChecks))
	}
	b.WriteByte('\n')
}

func codeList(values []string) string {
	if len(values) == 0 {
		return "_none_"
	}
	quoted := make([]string, 0, len(values))
	for _, value := range values {
		quoted = append(quoted, "`"+value+"`")
	}
	return strings.Join(quoted, ", ")
}
