package main

import (
	"fmt"
	"strings"
)

func renderPolicyTableDoc(loaded contract, rows []policyTableRow) string {
	var b strings.Builder
	fmt.Fprintln(&b, "# Store Channel Policy")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "<!-- Generated by go run ./tools/storecontract -write-policy-table. Do not edit by hand. -->")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "[Back to Store Channel Policy](../store-channel-policy.md)")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "Executable SSOT:")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "- [`policy-table.riido.json`](policy-table.riido.json)")
	fmt.Fprintln(&b, "- [`riido_daemon_store_distribution.riido.json`](../../../../packaging/store/riido_daemon_store_distribution.riido.json)")
	fmt.Fprintln(&b, "- `internal/policy.EvaluateStoreChannelPolicy`")
	fmt.Fprintln(&b)
	renderPolicyMatrix(&b, loaded, rows)
	renderPolicyNotes(&b)
	return b.String()
}

func renderPolicyMatrix(b *strings.Builder, loaded contract, rows []policyTableRow) {
	fmt.Fprint(b, "| Surface |")
	for _, item := range loaded.Channels {
		fmt.Fprintf(b, " `%s` |", item.ID)
	}
	fmt.Fprint(b, "\n| --- |")
	for range loaded.Channels {
		fmt.Fprint(b, " --- |")
	}
	fmt.Fprintln(b)
	for _, row := range rows {
		fmt.Fprintf(b, "| %s |", row.Surface)
		for _, cell := range row.Cells {
			fmt.Fprintf(b, " %s |", cell.Decision)
		}
		fmt.Fprintln(b)
	}
	fmt.Fprintln(b)
}

func renderPolicyNotes(b *strings.Builder) {
	fmt.Fprintln(b, "## Evaluation Rules")
	fmt.Fprintln(b)
	fmt.Fprintln(b, "- The table is generated by executing the C7 store channel policy decision function.")
	fmt.Fprintln(b, "- `requires ...` means the surface is allowed only when those reduced facts are true.")
	fmt.Fprintln(b, "- The tool does not inspect entitlements, install helpers, open IPC, or execute provider CLIs.")
	fmt.Fprintln(b, "- `dev-local` is not a package channel; policy code treats it as the Developer ID relaxation axis.")
}
