package main

import (
	"fmt"
	"strings"
)

func renderMarkdown(m Manifest) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# %s\n\n", m.Title)
	b.WriteString("<!-- Generated by go run ./tools/unsafebypassevidence -write-doc. Do not edit by hand. -->\n\n")
	b.WriteString("[Back to enforcement locations](../enforcement-locations.md)\n\n")
	b.WriteString("Executable SSOT: [`unsafe-bypass.riido.json`](unsafe-bypass.riido.json).\n\n")
	fmt.Fprintf(&b, "Evidence artifact: `%s`.\n\n", m.EvidenceArtifact)
	fmt.Fprintf(&b, "%s\n\n", m.Purpose)
	renderSurfaces(&b, m.Surfaces)
	renderAssertions(&b, m.Assertions)
	return b.String()
}

func renderSurfaces(b *strings.Builder, rows []Surface) {
	b.WriteString("## Enforcement Matrix\n\n")
	b.WriteString("| Provider | Surface | Flag | Enforcement | Host / Unknown default | Evidence |\n")
	b.WriteString("| --- | --- | --- | --- | --- | --- |\n")
	for _, row := range rows {
		fmt.Fprintf(
			b,
			"| %s | `%s` | `%s` | %s | %s | %s |\n",
			row.Provider,
			row.Surface,
			row.Flag,
			row.Enforcement,
			row.HostDefault,
			checkList(row.SourceChecks),
		)
	}
	b.WriteByte('\n')
}

func checkList(checks []string) string {
	return "`" + strings.Join(checks, "`, `") + "`"
}
