package main

import (
	"fmt"
	"strings"
)

func renderMarkdown(m manifest) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# %s\n\n", m.Title)
	b.WriteString("<!-- Generated by go run ./tools/providerintegrationevidence -write-doc. Do not edit by hand. -->\n\n")
	fmt.Fprintf(&b, "Executable SSOT: [`%s`](provider-real-cli-observation.riido.json).\n\n", m.ID)
	fmt.Fprintf(&b, "Public workflow: [`%s`](../../%s).\n\n", m.Workflow, m.Workflow)
	fmt.Fprintf(&b, "Evidence artifact: `%s`.\n\n", m.EvidenceArtifact)
	b.WriteString("## Provider Matrix\n\n")
	b.WriteString("| Provider | Executable | Override Env | Integration Command |\n")
	b.WriteString("| --- | --- | --- | --- |\n")
	for _, provider := range m.Providers {
		fmt.Fprintf(&b, "| %s | `%s` | `%s` | `%s` |\n",
			provider.DisplayName,
			provider.DefaultExecutable,
			provider.OverrideEnv,
			integrationCommand(provider),
		)
	}
	b.WriteString("\n## Semantics\n\n")
	b.WriteString("- Missing executables are recorded as observed `skipped`, not PASS.\n")
	b.WriteString("- Available executables run provider `TestIntegration` with `AGENTBRIDGE_INTEGRATION=1`.\n")
	b.WriteString("- Available-provider integration failure fails the workflow after writing evidence.\n")
	b.WriteString("- Cursor records auth preflight booleans for interactive login and `CURSOR_API_KEY` presence without serializing the secret value.\n")
	b.WriteString("- OpenClaw model speed is configured through OpenClaw itself; the integration test tries the verified faster `ollama/llama3.2:latest` first, then falls back to `ollama/qwen3:8b` and `ollama/qwen2.5-coder:1.5b`, records candidates in evidence, and can be pinned with `RIIDO_OPENCLAW_INTEGRATION_MODEL` before QA.\n")
	b.WriteString("- OpenClaw text completion does not prove daemon-selected cwd filesystem side effects; the integration artifact gate records that distinction explicitly.\n")
	b.WriteString("- Local daily evidence is fresh for 24h and records `expires_at` for dashboard gating.\n")
	b.WriteString("\n## Local Daily Evidence\n\n")
	b.WriteString("```bash\n")
	b.WriteString("go run ./tools/providerintegrationevidence -check-doc -run-integration -valid-for 24h -evidence-out .riido-local/evidence/provider-real-cli-observation.json\n")
	b.WriteString("```\n")
	return b.String()
}
