package main

import (
	"fmt"
	"strings"
)

const generatedHeader = "<!-- Generated by go run ./tools/distributionhostdocs -write-doc. Do not edit by hand. -->"

func renderedDocs(m manifest) map[string]string {
	docs := map[string]string{m.GeneratedDoc: renderRoot(m)}
	for _, page := range m.Pages {
		docs[page.GeneratedDoc] = renderPage(page)
	}
	return docs
}

func renderDoc(title string, body func(*strings.Builder)) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# %s\n\n%s\n\n", title, generatedHeader)
	body(&b)
	return strings.TrimRight(b.String(), "\n") + "\n"
}

func writeBullets(b *strings.Builder, items []string) {
	for _, item := range items {
		fmt.Fprintf(b, "- %s\n", item)
	}
}
