package main

import (
	"net/http"
	"strconv"
	"time"
)

func createAgentFixture(
	client apiClient,
	base string,
	index int,
	runtime preparedRuntime,
) (scenario, taskAgentCandidate) {
	name := agentFixtureName(index, runtime.Kind)
	body := map[string]any{
		"name":        name,
		"runtime_id":  runtime.RuntimeID,
		"visibility":  "private",
		"description": "Generated by local product acceptance; safe to delete.",
		"instruction": "Reply briefly and avoid destructive changes during local QA.",
	}
	sc, payload := apiQueryPayload(client, agentCreateScenarioID(index), http.MethodPost,
		base+"/agents", body, summarizeAgentCreate)
	candidate := taskAgentCandidate{
		AgentID:     agentIDFromCreatePayload(payload),
		RuntimeKind: runtime.Kind,
		RuntimeID:   runtime.RuntimeID,
		Name:        name,
	}
	return sc, candidate
}

func agentFixtureName(index int, kind string) string {
	return "Local QA " + kind + " " + strconv.Itoa(index) + " " +
		time.Now().UTC().Format("20060102T150405Z")
}

func agentCreateScenarioID(index int) string {
	return "local.saas.agent_fixture.create." + strconv.Itoa(index)
}
