package main

import (
	"fmt"
	"strings"
)

func renderDoc(m manifest, result verifyResult) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# %s\n\n", m.Title)
	fmt.Fprintln(&b, "<!-- Generated by go run ./tools/localqacandidatedecision -write-doc. Do not edit by hand. -->")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "Executable SSOT: [`local-qa-candidate-decision.riido.json`](local-qa-candidate-decision.riido.json).")
	fmt.Fprintln(&b)
	fmt.Fprintf(&b, "- evidence artifact: `%s`\n", m.EvidenceArtifact)
	fmt.Fprintf(&b, "- decision records: `%d`\n", len(m.Decisions))
	fmt.Fprintln(&b)
	renderAssertions(&b, m.Assertions)
	renderDecisionTable(&b, m.Decisions)
	renderLoop(&b, m.Loop)
	return strings.TrimRight(b.String(), "\n") + "\n"
}

func renderAssertions(b *strings.Builder, assertions []string) {
	fmt.Fprintln(b, "## Assertions")
	fmt.Fprintln(b)
	for _, assertion := range assertions {
		fmt.Fprintf(b, "- %s\n", assertion)
	}
	fmt.Fprintln(b)
}
