package main

const (
	defaultManifest = "docs/30-architecture/workflow-evidence.riido.json"
	evidenceSchema  = "riido-daemon-workflow-evidence.v1"
	generatedNotice = "<!-- Generated by go run ./tools/workflowevidence -write-doc. Do not edit by hand. -->"
)
