package main

import (
	"bytes"
	"fmt"
)

func render(manifest Manifest) string {
	var b bytes.Buffer
	fmt.Fprintf(&b, "# %s\n\n", manifest.Title)
	b.WriteString("<!-- Generated by go run ./tools/compatibilitygate -write-doc. Do not edit by hand. -->\n\n")
	b.WriteString("Executable SSOT: [`compatibility-gate.riido.json`](compatibility-gate.riido.json).\n\n")
	fmt.Fprintf(&b, "Evidence artifact: `%s`.\n\n", manifest.EvidenceArtifact)
	fmt.Fprintf(&b, "%s\n\n", manifest.Purpose)
	writeInputs(&b, manifest.Inputs)
	writeGateOrder(&b, manifest.GateOrder)
	writeOutputs(&b, manifest.Outputs)
	writeFailureSemantics(&b, manifest.FailureSemantics)
	writeAssertions(&b, manifest.Assertions)
	return b.String()
}

func writeInputs(b *bytes.Buffer, inputs []GateInput) {
	b.WriteString("## Gate Inputs\n\n| Input | Owner | Evidence |\n| --- | --- | --- |\n")
	for _, input := range inputs {
		fmt.Fprintf(b, "| %s | %s | `%s` |\n", input.Name, input.Owner, joinRefs(input.SourceChecks))
	}
}

func writeGateOrder(b *bytes.Buffer, steps []GateStep) {
	b.WriteString("\n## Gate Order\n\n")
	for i, step := range steps {
		fmt.Fprintf(b, "%d. `%s` - %s (`%s`)\n", i+1, step.Step, step.Summary, joinRefs(step.SourceChecks))
	}
}
