package main

import (
	"fmt"
	"strings"
)

func renderMarkdown(manifest Manifest, policy PolicySnapshot) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# %s\n\n", manifest.Title)
	fmt.Fprintln(&b, "<!-- Generated by go run ./tools/privacymetadata -write-doc. Do not edit by hand. -->")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "[Back to Store Channel Policy](../store-channel-policy.md)")
	fmt.Fprintln(&b)
	fmt.Fprintf(&b, "Executable SSOT: [`%s`](../../../../%s).\n\n", manifest.PolicyArtifact, manifest.PolicyArtifact)
	fmt.Fprintf(&b, "Evidence manifest: [`server-facing-metadata.riido.json`](server-facing-metadata.riido.json).\n\n")
	fmt.Fprintf(&b, "Evidence artifact: `%s`.\n\n", manifest.EvidenceArtifact)
	fmt.Fprintf(&b, "%s\n\n", manifest.Purpose)
	renderSurfaces(&b, policy)
	renderRules(&b, policy)
	return b.String()
}

func renderSurfaces(b *strings.Builder, policy PolicySnapshot) {
	for _, surface := range policy.Surfaces {
		renderSurface(b, surface)
	}
}
