package main

import (
	"fmt"
	"strings"
)

const generatedHeader = "<!-- Generated by go run ./tools/figmaboundarydocs -write-doc. Do not edit by hand. -->"

func renderDoc(title string, body func(*strings.Builder)) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# %s\n\n%s\n\n", title, generatedHeader)
	b.WriteString("[Back to Figma AI Agent Daemon Boundary](../figma-ai-agent-daemon-boundary.md)\n\n")
	body(&b)
	return strings.TrimRight(b.String(), "\n") + "\n"
}

func writeBullets(b *strings.Builder, items []string) {
	for _, item := range items {
		fmt.Fprintf(b, "- %s\n", item)
	}
	b.WriteByte('\n')
}

func sentenceList(items []string) string {
	if len(items) == 0 {
		return ""
	}
	return strings.Join(items, ", ")
}
