package project

import (
	"github.com/teamswyg/riido-daemon/internal/mwsdbridge"
)

func sampleSnapshot() mwsdbridge.Snapshot {
	return mwsdbridge.Snapshot{
		Status: mwsdbridge.Status{
			Root:                       "/workspace",
			GraphSchemaVersion:         mwsdbridge.GraphSchemaVersion,
			DomainSchemaVersion:        mwsdbridge.DomainSchemaVersion,
			HarnessSchemaVersion:       mwsdbridge.HarnessSchemaVersion,
			OrchestrationSchemaVersion: mwsdbridge.OrchestrationSchemaVersion,
			DocumentCount:              23,
			RepositoryCount:            3,
			DomainName:                 "macmini-workspace",
			HarnessRunCount:            2,
			HarnessNextDirection:       "top-down",
			HarnessRecentDirections:    []string{"top-down", "bottom-up"},
		},
		Graph: mwsdbridge.GraphExport{
			SchemaVersion: mwsdbridge.GraphSchemaVersion,
			Root:          "/workspace",
			Documents: []mwsdbridge.Document{
				{
					Path:   "README.md",
					Links:  []string{"docs/GOAL.md"},
					Status: "",
				},
				{
					Path:   "docs/ROADMAP.md",
					ID:     "mws.roadmap",
					Title:  "로드맵",
					Status: "seed",
					Owner:  "local",
				},
				{
					Path:   "docs/GOAL.md",
					ID:     "mws.goal",
					Title:  "목표",
					Status: "seed",
					Owner:  "local",
				},
			},
			Stats: mwsdbridge.GraphStats{
				DocumentCount: 23,
				NodeCount:     23,
				EdgeCount:     100,
			},
		},
		Domain: mwsdbridge.DomainExport{
			SchemaVersion: mwsdbridge.DomainSchemaVersion,
			Path:          "/workspace/domains/macmini-workspace.lisp",
			Domain:        "macmini-workspace",
		},
		Harness: mwsdbridge.HarnessIndex{
			SchemaVersion:    mwsdbridge.HarnessSchemaVersion,
			Path:             "/workspace/harness/runs.jsonl",
			RunCount:         2,
			TopDownCount:     1,
			BottomUpCount:    1,
			LastDirection:    "bottom-up",
			NextDirection:    "top-down",
			RecentDirections: []string{"top-down", "bottom-up"},
		},
		Orchestration: mwsdbridge.OrchestrationSnapshot{
			SchemaVersion:          mwsdbridge.OrchestrationSchemaVersion,
			Root:                   "/workspace",
			DomainPath:             "/workspace/domains/macmini-workspace.lisp",
			HarnessRunPath:         "/workspace/harness/runs.jsonl",
			DomainSchemaVersion:    mwsdbridge.DomainSchemaVersion,
			HarnessSchemaVersion:   mwsdbridge.HarnessSchemaVersion,
			Mode:                   "orchestration-over-choreography",
			DecisionGate:           "human-approval-required",
			DecisionBy:             []string{"human"},
			DecisionLLMs:           []string{"codex"},
			RecommendedProvider:    "codex",
			RecommendedDecisionLLM: "codex",
			ProviderCandidates: []mwsdbridge.ProviderCandidate{
				{ID: "codex", SourceWorkflow: "provider-selection", Available: true, ApprovalRequired: true},
				{ID: "claude-code", SourceWorkflow: "provider-selection", Available: true, ApprovalRequired: true},
				{ID: "cursor", SourceWorkflow: "provider-selection", Available: true, ApprovalRequired: true},
			},
			NextAction: mwsdbridge.OrchestrationNextAction{
				Direction:             "top-down",
				CommandSurface:        "mwsd harness + riido task queue + mws-viewer cockpit",
				Reason:                "lift the latest bottom-up evidence into the next SSOT plan",
				RequiresHumanApproval: true,
			},
			TopDownCount:  1,
			BottomUpCount: 1,
			LastDirection: "bottom-up",
			Balanced:      true,
			DirectionBias: false,
			RecentRuns: []mwsdbridge.OrchestrationRun{
				{ID: "run-1", Direction: "top-down", Source: "docs/ROADMAP.md", Provider: "codex", Command: "plan", Result: "passed"},
			},
		},
		Projects: mwsdbridge.ProjectRegistry{
			SchemaVersion:   mwsdbridge.ProjectsSchemaVersion,
			Root:            "/workspace",
			DomainPath:      "/workspace/domains/macmini-workspace.lisp",
			RepositoryCount: 3,
			Repositories: []mwsdbridge.ProjectRepository{
				{
					Name:          "macmini-workspace",
					Owner:         "kimjooyoon",
					Visibility:    "private",
					SSOTScope:     "workspace-control-plane",
					LocalPath:     "/Users/teddy/github/kimjooyoon/macmini-workspace",
					Remote:        "https://github.com/kimjooyoon/macmini-workspace",
					Role:          "control-plane",
					LocalPresent:  true,
					GitPresent:    true,
					RemoteMatches: true,
				},
				{
					Name:          "gui_engine",
					Owner:         "kimjooyoon",
					Visibility:    "private",
					SSOTScope:     "gui-engine",
					LocalPath:     "/Users/teddy/github/kimjooyoon/gui_engine",
					Remote:        "https://github.com/kimjooyoon/gui_engine",
					Role:          "gui-runtime",
					LocalPresent:  true,
					GitPresent:    true,
					RemoteMatches: true,
				},
				{
					Name:          "riido-daemon",
					Owner:         "kimjooyoon",
					Visibility:    "private",
					SSOTScope:     "project-daemon",
					LocalPath:     "/Users/teddy/github/kimjooyoon/riido-daemon",
					Remote:        "https://github.com/teamswyg/riido-daemon",
					Role:          "project-ssot",
					LocalPresent:  true,
					GitPresent:    true,
					RemoteMatches: true,
				},
			},
		},
	}
}
