package main

import (
	"fmt"
	"strings"
)

func renderMarkdown(m Manifest) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# %s\n\n", m.Title)
	b.WriteString("<!-- Generated by go run ./tools/runtimeeligibility -write-doc. Do not edit by hand. -->\n\n")
	b.WriteString("[Back to invariants](../invariants.md)\n\n")
	b.WriteString("Executable SSOT: [`runtime-eligibility.riido.json`](runtime-eligibility.riido.json).\n\n")
	fmt.Fprintf(&b, "Evidence artifact: `%s`.\n\n", m.EvidenceArtifact)
	fmt.Fprintf(&b, "%s\n\n", m.Purpose)
	renderInputs(&b, m.Inputs)
	renderGates(&b, m.Gates)
	renderPassthroughs(&b, m.Passthroughs)
	renderAbsentScans(&b, m.AbsentScans)
	renderAssertions(&b, m.Assertions)
	return b.String()
}

func renderInputs(b *strings.Builder, rows []Input) {
	b.WriteString("## Eligibility Inputs\n\n")
	b.WriteString("| Input | Source | Evidence |\n| --- | --- | --- |\n")
	for _, row := range rows {
		fmt.Fprintf(b, "| `%s` | %s | %s |\n", row.Name, row.Source, checks(row.SourceChecks))
	}
	b.WriteByte('\n')
}

func renderGates(b *strings.Builder, rows []Gate) {
	b.WriteString("## Gate Order\n\n")
	b.WriteString("| Order | Reason code | Rule | Evidence |\n| --- | --- | --- | --- |\n")
	for _, row := range rows {
		fmt.Fprintf(b, "| %d | `%s` | %s | %s |\n", row.Order, row.Code, row.Summary, checks(row.SourceChecks))
	}
	b.WriteByte('\n')
}

func checks(names []string) string {
	return "`" + strings.Join(names, "`, `") + "`"
}
