package main

import (
	"fmt"
	"strings"
)

func renderMarkdown(m Manifest) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# %s\n\n", m.Title)
	b.WriteString("<!-- Generated by go run ./tools/taskrequirements -write-doc. Do not edit by hand. -->\n\n")
	b.WriteString("[Back to invariants](../invariants.md)\n\n")
	b.WriteString("Executable SSOT: [`task-requirements.riido.json`](task-requirements.riido.json).\n\n")
	fmt.Fprintf(&b, "Evidence artifact: `%s`.\n\n", m.EvidenceArtifact)
	fmt.Fprintf(&b, "%s\n\n", m.Purpose)
	renderSurfaceTable(&b, m.Surfaces)
	renderInputs(&b, m.Inputs)
	renderExample(&b)
	renderAssertions(&b, m.Assertions)
	return b.String()
}

func renderSurfaceTable(b *strings.Builder, rows []Surface) {
	b.WriteString("## Required Surfaces\n\n")
	b.WriteString("| Surface | Meaning | Capability flag | Scheduling field | Evidence |\n")
	b.WriteString("| --- | --- | --- | --- | --- |\n")
	for _, row := range rows {
		fmt.Fprintf(b, "| `%s` | %s | `%s` | `%s` | %s |\n",
			row.Name, row.Meaning, row.CapabilityFlag, row.CandidateField, checks(row.SourceChecks))
	}
	b.WriteByte('\n')
}

func checks(names []string) string {
	return "`" + strings.Join(names, "`, `") + "`"
}
