package main

import (
	"fmt"
	"strings"
)

const baseDir = "docs/30-architecture/agent-execution-unresolved-design/"

func renderDoc(title, backText, backPath string, body func(*strings.Builder)) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# %s\n\n", title)
	b.WriteString("<!-- Generated by go run ./tools/agentexecutiondesign -write-doc. Do not edit by hand. -->\n\n")
	if backText != "" {
		fmt.Fprintf(&b, "[Back to %s](%s)\n\n", backText, backPath)
	}
	body(&b)
	return strings.TrimRight(b.String(), "\n") + "\n"
}

func writeBullets(b *strings.Builder, items []string) {
	for _, item := range items {
		fmt.Fprintf(b, "- %s\n", item)
	}
}

func writeNumbered(b *strings.Builder, items []string) {
	for i, item := range items {
		fmt.Fprintf(b, "%d. %s\n", i+1, item)
	}
}
