package main

import (
	"fmt"
	"strings"
)

func renderMarkdown(m manifest) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# %s\n\n", m.Title)
	b.WriteString("<!-- Generated by go run ./tools/selfimprovementevidence -write-doc. Do not edit by hand. -->\n\n")
	fmt.Fprintf(&b, "- SSOT: `%s`\n", defaultManifest)
	fmt.Fprintf(&b, "- Workflow: `%s`\n", m.Workflow)
	fmt.Fprintf(&b, "- Evidence artifact: `%s`\n", m.EvidenceArtifact)
	fmt.Fprintf(&b, "- Loop source: `%s`\n\n", m.LoopSource)
	b.WriteString("## Required Evidence\n\n")
	b.WriteString("| Evidence | File | Purpose |\n")
	b.WriteString("| --- | --- | --- |\n")
	for _, item := range m.Required {
		fmt.Fprintf(&b, "| `%s` | `%s` | %s |\n", item.ID, item.File, item.Description)
	}
	b.WriteString("\n## Assertions\n\n")
	b.WriteString("| Evidence | Field | Expected |\n")
	b.WriteString("| --- | --- | --- |\n")
	for _, item := range m.Required {
		renderAssertions(&b, item)
	}
	return strings.TrimRight(b.String(), "\n") + "\n"
}

func renderAssertions(b *strings.Builder, item requiredEvidence) {
	for _, assertion := range item.Assertions {
		expected := fmt.Sprintf("%v", assertion.Equals)
		if assertion.Empty {
			expected = "empty"
		}
		fmt.Fprintf(b, "| `%s` | `%s` | `%s` |\n", item.ID, assertion.Field, expected)
	}
}
