package main

import (
	"fmt"
	"strings"
)

func renderMarkdown(manifest Manifest, fsm FSMSnapshot) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# %s\n\n", manifest.Title)
	fmt.Fprintln(&b, "<!-- Generated by go run ./tools/assignmentfsm -write-doc. Do not edit by hand. -->")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "[Back to agent-execution-unresolved-design.md](../agent-execution-unresolved-design.md)")
	fmt.Fprintln(&b)
	fmt.Fprintf(&b, "Executable SSOT: [`assignment-lifecycle-fsm.riido.json`](assignment-lifecycle-fsm.riido.json).\n\n")
	fmt.Fprintf(&b, "Contract source: `%s`.\n\n", manifest.SourcePackage)
	fmt.Fprintf(&b, "Evidence manifest: [`%s`](assignment-lifecycle-evidence.riido.json).\n\n", manifest.EvidenceManifest)
	fmt.Fprintf(&b, "%s\n\n", manifest.Purpose)
	renderMermaid(&b, fsm)
	renderMetadata(&b, fsm)
	renderRelated(&b, manifest)
	return b.String()
}

func renderMermaid(b *strings.Builder, fsm FSMSnapshot) {
	fmt.Fprintln(b, "## Generated Diagram")
	fmt.Fprintln(b)
	fmt.Fprintln(b, "```mermaid")
	fmt.Fprint(b, fsm.Mermaid)
	fmt.Fprintln(b, "```")
	fmt.Fprintln(b)
}
