package main

import (
	"bytes"
	"fmt"
)

func renderDoc(manifest Manifest) string {
	var b bytes.Buffer
	fmt.Fprintf(&b, "# %s\n\n", manifest.Title)
	b.WriteString("<!-- Generated by go run ./tools/branchgate -write-doc. Do not edit by hand. -->\n\n")
	b.WriteString("Executable SSOT: [`riido-work-branch-gate.riido.json`](riido-work-branch-gate.riido.json).\n\n")
	fmt.Fprintf(&b, "Evidence artifact: `%s`.\n\n", manifest.EvidenceArtifact)
	fmt.Fprintf(&b, "Shape: `%s`\n\nPattern: `%s`\n\n", manifest.Shape, manifest.Pattern)
	writeRules(&b, manifest.Rules)
	writeExamples(&b, manifest.Examples)
	writeAssertions(&b, manifest.Assertions)
	fmt.Fprintf(&b, "\nExecutable gate: `%s`.\n\n", manifest.GeneratedScript)
	fmt.Fprintf(&b, "PR workflow: `%s`.\n", manifest.Workflow)
	return b.String()
}

func writeRules(b *bytes.Buffer, rules []string) {
	b.WriteString("## Rules\n\n")
	for _, rule := range rules {
		fmt.Fprintf(b, "- %s\n", rule)
	}
}
