package main

import "fmt"

func renderScript(manifest Manifest) string {
	return fmt.Sprintf(`#!/usr/bin/env bash
set -euo pipefail

# Generated by go run ./tools/branchgate -write-script. Do not edit by hand.

branch="${1:-}"

if [[ -z "$branch" ]]; then
  echo "usage: $0 <branch-name>" >&2
  exit 2
fi

if [[ "$branch" == "main" ]]; then
  exit 0
fi

if [[ "$branch" == *"/"* ]]; then
  echo "branch must be the exact Riido branchName, not a namespaced local helper branch: $branch" >&2
  exit 1
fi

if [[ "$branch" =~ [[:space:]] ]]; then
  echo "branch must not contain whitespace: $branch" >&2
  exit 1
fi

if [[ ! "$branch" =~ %s ]]; then
  echo "branch must start with a Riido task key and slug, for example %s" >&2
  echo "actual: $branch" >&2
  exit 1
fi

`, manifest.Pattern, manifest.Example)
}
