package main

import "strings"

const generatedHeader = "<!-- Generated by go run ./tools/workspacedocs -write-doc. Do not edit by hand. -->"

func renderDoc(title string, body func(*strings.Builder)) string {
	var b strings.Builder
	b.WriteString("# " + title + "\n\n")
	b.WriteString(generatedHeader + "\n\n")
	body(&b)
	return strings.TrimRight(b.String(), "\n") + "\n"
}
