package main

import (
	"fmt"
	"strings"
)

func renderMarkdown(m manifest) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# %s\n\n", m.Title)
	b.WriteString("<!-- Generated by go run ./tools/runtimesecretevidence -write-doc. Do not edit by hand. -->\n\n")
	fmt.Fprintf(&b, "Executable SSOT: [`%s`](runtime-secret-private-evidence.riido.json).\n\n", m.ID)
	fmt.Fprintf(&b, "Public workflow: [`%s`](../../%s).\n\n", m.Workflow, m.Workflow)
	fmt.Fprintf(&b, "Private owner: `%s`.\n\n", m.PrivateOwner)
	renderList(&b, "Public Scope", m.PublicScope)
	renderKinds(&b, m.EvidenceKinds)
	renderList(&b, "Allowed Packet Fields", m.AllowedPacketFields)
	renderList(&b, "Allowed AWS Operations", m.AllowedAWSOperations)
	renderList(&b, "Forbidden AWS Operations", m.ForbiddenAWSOps)
	renderList(&b, "Forbidden Field Names", m.ForbiddenFieldNames)
	b.WriteString("## Semantics\n\n")
	b.WriteString("- Public CI validates the packet contract without reading private secret values.\n")
	b.WriteString("- Private infra evidence may satisfy this contract only with metadata fields.\n")
	b.WriteString("- Any raw secret field or decrypt/read operation is a contract failure.\n")
	return b.String()
}

func renderKinds(b *strings.Builder, kinds []evidenceKind) {
	b.WriteString("## Evidence Kinds\n\n")
	b.WriteString("| Kind | Actual ID | Proves | Forbids |\n")
	b.WriteString("| --- | --- | --- | --- |\n")
	for _, kind := range kinds {
		fmt.Fprintf(b, "| `%s` | `%s` | %s | %s |\n",
			kind.ID, kind.ActualID, strings.Join(kind.Proves, "; "), strings.Join(kind.Forbids, "; "))
	}
	b.WriteByte('\n')
}

func renderList(b *strings.Builder, title string, values []string) {
	fmt.Fprintf(b, "## %s\n\n", title)
	for _, value := range values {
		fmt.Fprintf(b, "- `%s`\n", value)
	}
	b.WriteByte('\n')
}
