package main

import (
	"fmt"
	"strings"
)

func renderDoc(reg registry) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# %s\n\n", reg.Title)
	b.WriteString("<!-- Generated by go run ./tools/loopregistry -write-doc. Do not edit by hand. -->\n\n")
	fmt.Fprintf(&b, "- Registry: `%s`\n", reg.ID)
	fmt.Fprintf(&b, "- Workflow: `%s`\n", reg.Workflow)
	fmt.Fprintf(&b, "- Evidence: `%s`\n\n", reg.EvidenceArtifact)
	renderLoopSummary(&b, reg)
	renderBusinessClaims(&b, reg.BusinessClaims)
	return strings.TrimRight(b.String(), "\n") + "\n"
}

func renderLoopSummary(b *strings.Builder, reg registry) {
	b.WriteString("## Loops\n\n")
	for _, item := range reg.Loops {
		fmt.Fprintf(b, "### %s\n\n", item.ID)
		fmt.Fprintf(b, "- Owner: `%s`\n", item.Owner)
		fmt.Fprintf(b, "- Kind: `%s`\n", item.Kind)
		fmt.Fprintf(b, "- Expires after: `%s`\n", item.ExpiresAfter)
		fmt.Fprintf(b, "- Observes: `%s`\n", strings.Join(item.Observes, "`, `"))
		fmt.Fprintf(b, "- Verifies: `%s`\n", strings.Join(item.Verifies, "`, `"))
		fmt.Fprintf(b, "- Fails when: `%s`\n\n", strings.Join(item.FailsWhen, "`, `"))
	}
}

func renderBusinessClaims(b *strings.Builder, claims []businessClaim) {
	b.WriteString("## Business Claims\n\n")
	for _, claim := range claims {
		fmt.Fprintf(b, "### %s\n\n", claim.ID)
		fmt.Fprintf(b, "%s\n\n", claim.Text)
		fmt.Fprintf(b, "- Files: `%s`\n", strings.Join(claim.Files, "`, `"))
		fmt.Fprintf(b, "- Docs: `%s`\n", strings.Join(claim.Docs, "`, `"))
		fmt.Fprintf(b, "- Evidence: `%s`\n", strings.Join(claim.Evidence, "`, `"))
		fmt.Fprintf(b, "- Verifiers: `%s`\n\n", strings.Join(checkNames(claim.Verifiers), "`, `"))
	}
}

func checkNames(checks []sourceCheck) []string {
	out := make([]string, 0, len(checks))
	for _, check := range checks {
		out = append(out, check.Name)
	}
	return out
}
