// Code generated by tools/riidogen from native_config_plan.riido.json; DO NOT EDIT.

package workdir

const (
	NativeConfigPlanSchemaVersion     = "riido-native-config-plan.v1"
	NativeConfigManifestSchemaVersion = "riido-native-config-manifest.v1"
	NativeConfigManifestPath          = ".riido/native-config-manifest.json"
)

var defaultProviderConfigPlan = providerNativeConfigPlan(
	"",
	"AGENTS.md",
	".riido/native-config-manifest.json",
	"instruction-only",
	"",
	nil,
	nil,
	nil,
)

var providerConfigPlans = map[string]ProviderNativeConfigPlan{
	"claude": providerNativeConfigPlan(
		"claude",
		"CLAUDE.md",
		".riido/native-config-manifest.json",
		"claude-command-hooks",
		"",
		[]string{".claude/settings.json"},
		[]string{".riido/hooks/claude-audit-hook.sh"},
		nil,
	),
	"codex": providerNativeConfigPlan(
		"codex",
		"AGENTS.md",
		".riido/native-config-manifest.json",
		"instruction-only",
		"",
		nil,
		nil,
		nil,
	),
	"cursor": providerNativeConfigPlan(
		"cursor",
		"AGENTS.md",
		".riido/native-config-manifest.json",
		"instruction-only",
		"",
		nil,
		nil,
		nil,
	),
	"gemini": providerNativeConfigPlan(
		"gemini",
		"GEMINI.md",
		".riido/native-config-manifest.json",
		"instruction-only",
		"",
		nil,
		nil,
		nil,
	),
	"openclaw": providerNativeConfigPlan(
		"openclaw",
		"AGENTS.md",
		".riido/native-config-manifest.json",
		"instruction-only",
		"",
		nil,
		nil,
		nil,
	),
}
