package main

import (
	"fmt"
	"strings"
)

func renderMarkdown(m Manifest) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# %s\n\n", m.Title)
	b.WriteString("<!-- Generated by go run ./tools/nativeconfigmcp -write-doc. Do not edit by hand. -->\n\n")
	b.WriteString("[Back to enforcement locations](../enforcement-locations.md)\n\n")
	b.WriteString("Executable SSOT: [`native-config-and-mcp.riido.json`](native-config-and-mcp.riido.json).\n\n")
	fmt.Fprintf(&b, "Evidence artifact: `%s`.\n\n%s\n\n", m.EvidenceArtifact, m.Purpose)
	renderFacts(&b, m.Facts)
	renderAbsent(&b, m.AbsentSurfaces)
	renderAssertions(&b, m.Assertions)
	return b.String()
}

func renderFacts(b *strings.Builder, rows []Fact) {
	b.WriteString("## Implemented Facts\n\n| Fact | Summary | Evidence |\n| --- | --- | --- |\n")
	for _, row := range rows {
		fmt.Fprintf(b, "| %s | %s | %s |\n", row.Name, row.Summary, checksList(row.SourceChecks))
	}
	b.WriteByte('\n')
}

func checksList(checks []string) string {
	return "`" + strings.Join(checks, "`, `") + "`"
}
