package main

import (
	"fmt"
	"strings"
)

func renderMarkdown(m manifest) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# %s\n\n", m.Title)
	b.WriteString("<!-- Generated by go run ./tools/loopevidence -write. Do not edit by hand. -->\n\n")
	b.WriteString("## Loop Vocabulary\n\n")
	for _, phase := range m.RequiredPhases {
		fmt.Fprintf(&b, "- `%s`\n", phase)
	}
	b.WriteString("\n## Evidence Loops\n\n")
	for _, item := range m.Loops {
		renderLoop(&b, item)
	}
	b.WriteString("## Open Gaps\n\n")
	if len(m.OpenGaps) == 0 {
		b.WriteString("_None._\n")
		return b.String()
	}
	for _, item := range m.OpenGaps {
		fmt.Fprintf(&b, "### %s\n\n", item.ID)
		fmt.Fprintf(&b, "- Owner: `%s`\n", item.Owner)
		fmt.Fprintf(&b, "- Current handling: %s\n", item.CurrentHandling)
		fmt.Fprintf(&b, "- Required next artifact: %s\n\n", item.RequiredNextArtifact)
	}
	return b.String()
}

func renderLoop(b *strings.Builder, item loop) {
	fmt.Fprintf(b, "### %s\n\n", item.ID)
	fmt.Fprintf(b, "- Owner: `%s`\n", item.Owner)
	renderPhase(b, "Observe", item.Observation)
	renderPhase(b, "Hypothesis", item.Hypothesis)
	renderPhase(b, "Execute", item.Execution)
	renderPhase(b, "Evaluate", item.Evaluation)
	renderPhase(b, "Retrospective", item.Retrospective)
	b.WriteString("- Evidence:\n")
	for _, ev := range item.Evidence {
		fmt.Fprintf(b, "  - `%s`: %s; proves %s\n", ev.Kind, ev.Ref, ev.Proves)
	}
	b.WriteString("\n")
}

func renderPhase(b *strings.Builder, name string, p phase) {
	fmt.Fprintf(b, "- %s: %s\n", name, p.Summary)
	if len(p.Artifacts) == 0 {
		return
	}
	fmt.Fprintf(b, "  - Artifacts: `%s`\n", strings.Join(p.Artifacts, "`, `"))
}
