package main

import (
	"fmt"
	"strings"
)

func renderMarkdown(m manifest) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# %s\n\n", m.Title)
	b.WriteString("<!-- Generated by go run ./tools/repoverification -write-doc. Do not edit by hand. -->\n\n")
	b.WriteString("Executable SSOT: [`verification.riido.json`](verification.riido.json).\n\n")
	fmt.Fprintf(&b, "Evidence artifact: `%s`.\n\n", m.EvidenceArtifact)
	b.WriteString("## Commands\n\n")
	for _, command := range m.Commands {
		fmt.Fprintf(&b, "### %s\n\n", command.ID)
		fmt.Fprintf(&b, "%s\n\n", command.Description)
		b.WriteString("```bash\n")
		fmt.Fprintf(&b, "%s\n", shellQuote(command.Argv))
		b.WriteString("```\n\n")
	}
	b.WriteString("## Assertions\n\n")
	for _, assertion := range m.Assertions {
		fmt.Fprintf(&b, "- %s\n", assertion)
	}
	return b.String()
}
