package main

import (
	"bytes"
	"fmt"
)

func render(manifest Manifest) string {
	var b bytes.Buffer
	fmt.Fprintf(&b, "# %s\n\n", manifest.Title)
	b.WriteString("<!-- Generated by go run ./tools/semanticeventactivity -write-doc. Do not edit by hand. -->\n\n")
	b.WriteString("Executable SSOT: [`idle-watchdog.riido.json`](idle-watchdog.riido.json).\n\n")
	fmt.Fprintf(&b, "Evidence artifact: `%s`.\n\n", manifest.EvidenceArtifact)
	b.WriteString("Idle watchdog resets only on events where the provider advances task meaning.\n\n")
	writeList(&b, "Semantic Activity", manifest.SemanticActivity)
	writeList(&b, "Non-Semantic Activity", manifest.NonSemanticActivity)
	writeList(&b, "Assertions", manifest.Assertions)
	b.WriteString("`progress` is produced by the common Riido telemetry parser from `<riido_log>{\"code\":...,\"args\":{...}}<end>`.\n")
	b.WriteString("Legacy raw phrases are compatibility fallback mappings into code/args.\n\n")
	b.WriteString("stderr heartbeat, log spam, or process signals alone must not reset the idle watchdog.\n")
	return b.String()
}

func writeList(b *bytes.Buffer, title string, values []string) {
	fmt.Fprintf(b, "## %s\n\n", title)
	for _, value := range values {
		fmt.Fprintf(b, "- `%s`\n", value)
	}
	b.WriteString("\n")
}
