package main

import "strings"

const generatedMarker = "<!-- Generated by "

func generatedDocCommand(text string) (string, bool) {
	_, rest, ok := strings.Cut(text, generatedMarker)
	if !ok {
		return "", false
	}
	if end := strings.Index(rest, "-->"); end >= 0 {
		rest = rest[:end]
	}
	return cleanGeneratedCommand(rest), true
}

func cleanGeneratedCommand(text string) string {
	text = strings.TrimSpace(strings.TrimSuffix(strings.TrimSpace(text), "."))
	text = strings.TrimSpace(strings.TrimSuffix(text, "Do not edit by hand"))
	return strings.TrimSpace(strings.TrimSuffix(text, "."))
}
