package main

import "testing"

func TestGeneratedOriginsSummarizeGeneratorCommands(t *testing.T) {
	docs := []docClass{
		{Path: "docs/a.md", Kind: "generated", Generator: "go run ./tools/a -write-doc"},
		{Path: "docs/b.md", Kind: "generated", Generator: "go run ./tools/a -write-doc"},
		{Path: "docs/c.md", Kind: "generated", Generator: "go run ./tools/c -write-doc"},
	}

	got := generatedOrigins(docs)
	if len(got) != 2 || got[0].Count != 2 || got[0].Generator != "go run ./tools/a -write-doc" {
		t.Fatalf("origins = %#v", got)
	}
}

func TestGeneratedDocCommandStripsBoilerplate(t *testing.T) {
	text := "<!-- Generated by go run ./tools/x -write-doc. Do not edit by hand. -->\n"
	got, ok := generatedDocCommand(text)
	if !ok || got != "go run ./tools/x -write-doc" {
		t.Fatalf("generated command = %q, %v", got, ok)
	}
}
