package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestLoadManifestRejectsMalformedUnknownAndTrailingJSON(t *testing.T) {
	dir := t.TempDir()
	cases := []struct {
		name string
		body string
		want string
	}{
		{name: "malformed", body: "{", want: "decode manifest"},
		{name: "unknown", body: `{"schema_version":"riido-executable-knowledge-coverage.v1","extra":true}`, want: "unknown field"},
		{name: "trailing", body: `{"schema_version":"riido-executable-knowledge-coverage.v1"}{}`, want: "one JSON value"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			path := filepath.Join(dir, tc.name+".json")
			writeFixture(t, dir, tc.name+".json", tc.body)
			if _, err := loadManifest(path); err == nil || !strings.Contains(err.Error(), tc.want) {
				t.Fatalf("expected %q error, got %v", tc.want, err)
			}
		})
	}
}

func TestKnowledgeCoverageWritesFailedEvidenceBeforeReturningProblems(t *testing.T) {
	root := t.TempDir()
	writeFixture(t, root, "docs/30-architecture/known.md", "# Known\n")
	writeFixture(t, root, "docs/30-architecture/unknown.md", "# Unknown\n")
	writeFixture(t, root, "docs/30-architecture/executable-knowledge.md", "<!-- Generated by fixture. -->\n")
	writeManifest(t, root, fixtureManifest())
	out := "evidence.json"
	err := run(root, "manifest.json", out, false, false)
	if err == nil || !strings.Contains(err.Error(), "knowledge coverage invalid") {
		t.Fatalf("expected knowledge coverage problem, got %v", err)
	}
	data, readErr := os.ReadFile(filepath.Join(root, out))
	if readErr != nil || !strings.Contains(string(data), `"status": "failed"`) {
		t.Fatalf("failed evidence missing: err=%v body=%s", readErr, data)
	}
}

func TestKnowledgeCoverageIOHelpersReportWriteFailures(t *testing.T) {
	dir := t.TempDir()
	blocked := filepath.Join(dir, "blocked")
	writeFixture(t, dir, "blocked", "file")
	if err := writeText(filepath.Join(blocked, "doc.md"), "x"); err == nil {
		t.Fatal("expected writeText directory failure")
	}
	if err := writeJSON(filepath.Join(blocked, "evidence.json"), map[string]string{"ok": "yes"}); err == nil {
		t.Fatal("expected writeJSON directory failure")
	}
	if err := writeJSON(filepath.Join(dir, "bad.json"), map[string]any{"bad": make(chan int)}); err == nil {
		t.Fatal("expected writeJSON marshal failure")
	}
	if got := joinProblems([]string{"a", "b"}); got != "a\n- b" {
		t.Fatalf("joinProblems=%q", got)
	}
}

func writeManifest(t *testing.T, root string, m manifest) {
	t.Helper()
	if err := writeJSON(filepath.Join(root, "manifest.json"), m); err != nil {
		t.Fatal(err)
	}
}
