package main

import "testing"

func TestKnowledgeCoverageRequiresEvidenceLoop(t *testing.T) {
	root := t.TempDir()
	writeFixture(t, root, "docs/30-architecture/executable-knowledge.md", "<!-- Generated by fixture. -->\n")
	m := fixtureManifest()
	m.Loop = evidenceLoop{}
	problems := validateManifest(root, m)
	if !containsProblem(problems, "loop observation is required") {
		t.Fatalf("expected missing loop problem: %v", problems)
	}
}
