package main

import (
	"strings"
	"testing"
)

func TestKnowledgeCoverageRequiresLoopRegistryFields(t *testing.T) {
	root := t.TempDir()
	writeFixture(t, root, "docs/30-architecture/executable-knowledge.md", "<!-- Generated by fixture. -->\n")
	m := fixtureManifest()
	m.LoopRegistry = []loopRegistryEntry{{
		ID:         "local-qa-daily-evidence-sweep",
		LoopSource: "docs/30-architecture/executable-knowledge.md",
	}}
	problems := validateManifest(root, m)
	if !containsProblem(problems, "must declare observes, verifies, evidence, and fails_when") {
		t.Fatalf("expected loop registry problem: %v", problems)
	}
}

func TestRenderDocShowsLoopRegistry(t *testing.T) {
	root := t.TempDir()
	writeFixture(t, root, "docs/30-architecture/executable-knowledge.md", "<!-- Generated by fixture. -->\n")
	m := fixtureManifest()
	got := renderDoc(root, m, nil, nil)
	if !strings.Contains(got, "## Loop Registry") || !strings.Contains(got, "fixture-loop") {
		t.Fatalf("expected loop registry in generated doc:\n%s", got)
	}
}
