package main

import (
	"fmt"
	"strings"
)

func renderDoc(m manifest, docs []docClass, problems []string) string {
	e := buildEvidence(m, docs, problems)
	var b strings.Builder
	b.WriteString("# " + m.Title + "\n\n")
	b.WriteString("<!-- Generated by go run ./tools/knowledgecoverage -write-doc. Do not edit by hand. -->\n\n")
	b.WriteString("Executable SSOT: [`executable-knowledge.riido.json`](executable-knowledge.riido.json).\n\n")
	b.WriteString("## Coverage\n\n")
	b.WriteString("| Class | Count |\n| --- | ---: |\n")
	fmt.Fprintf(&b, "| Generated reader docs | %d |\n", e.GeneratedCount)
	fmt.Fprintf(&b, "| Direct SSOT docs | %d |\n", e.DirectSSOTCount)
	fmt.Fprintf(&b, "| Registered manual docs | %d |\n", e.ManualCount)
	fmt.Fprintf(&b, "| Scanned docs | %d |\n\n", e.ScannedCount)
	b.WriteString("## Registered Manual Surfaces\n\n")
	byGroup := e.ManualByGroup
	b.WriteString("| Group | Owner | Next artifact | Matched docs |\n| --- | --- | --- | ---: |\n")
	for _, group := range m.ManualGroups {
		fmt.Fprintf(&b, "| `%s` | %s | %s | %d |\n", group.ID, group.Owner, group.NextArtifact, byGroup[group.ID])
	}
	b.WriteString("\n## Assertions\n\n")
	for _, assertion := range m.Assertions {
		b.WriteString("- " + assertion + "\n")
	}
	return b.String()
}
