package main

import (
	"strings"
	"testing"
)

func TestKnowledgeCoverageRepositoryManifest(t *testing.T) {
	err := run("../..", "docs/30-architecture/executable-knowledge.riido.json", "", false, true)
	if err != nil {
		t.Fatal(err)
	}
}

func TestKnowledgeCoverageFindsUnregisteredManualDoc(t *testing.T) {
	root := t.TempDir()
	writeFixture(t, root, "docs/30-architecture/known.md", "# Known\n")
	writeFixture(t, root, "docs/30-architecture/unknown.md", "# Unknown\n")
	writeFixture(t, root, "docs/30-architecture/executable-knowledge.md", "<!-- Generated by fixture. -->\n")

	m := fixtureManifest()
	docs, problems := scanDocs(root, m)
	if len(docs) != 3 {
		t.Fatalf("docs len = %d", len(docs))
	}
	if len(problems) == 0 {
		t.Fatal("expected unregistered manual doc problem")
	}
}

func TestKnowledgeCoverageAllowsZeroManualGroups(t *testing.T) {
	root := t.TempDir()
	writeFixture(t, root, "docs/30-architecture/executable-knowledge.md", "<!-- Generated by fixture. -->\n")
	m := fixtureManifest()
	m.ManualGroups = nil
	if problems := validateManifest(root, m); len(problems) != 0 {
		t.Fatalf("zero manual groups should be valid: %v", problems)
	}
}

func TestRenderDocShowsNoneForZeroManualDebt(t *testing.T) {
	m := fixtureManifest()
	m.ManualGroups = nil
	got := renderDoc(m, []docClass{{Path: "docs/generated.md", Kind: "generated"}}, nil)
	if strings.Count(got, "_None._") != 3 {
		t.Fatalf("expected all manual sections to show none:\n%s", got)
	}
}

func TestKnowledgeCoverageManualPrefixRegistersOnlyManualDocs(t *testing.T) {
	root := t.TempDir()
	writeFixture(t, root, "docs/domain/manual.md", "# Manual\n")
	writeFixture(t, root, "docs/domain/generated.md", "<!-- Generated by fixture. -->\n")
	m := fixtureManifest()
	m.ScanRoots = []string{"docs/domain"}
	m.ManualGroups[0].Paths = nil
	m.ManualGroups[0].PathPrefixes = []string{"docs/domain/"}
	docs, problems := scanDocs(root, m)
	if len(problems) != 0 {
		t.Fatalf("prefix should register manual docs: %v", problems)
	}
	counts := countDocs(docs)
	if counts["manual_registered"] != 1 || counts["generated"] != 1 {
		t.Fatalf("counts = %#v", counts)
	}
}
