package main

import (
	"fmt"
	"strings"
)

func renderDetailDoc(manifest Manifest, doc DetailDoc) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# %s\n\n", doc.Title)
	b.WriteString("<!-- Generated by go run ./tools/configreference -write-doc. Do not edit by hand. -->\n\n")
	b.WriteString("[Back to Daemon Config Reference](../config-reference.md)\n\n")
	for _, block := range doc.Blocks {
		renderDetailBlock(&b, manifest, block)
	}
	return strings.TrimRight(b.String(), "\n") + "\n"
}

func renderDetailBlock(b *strings.Builder, manifest Manifest, block DetailBlock) {
	switch block.Kind {
	case "paragraph":
		fmt.Fprintf(b, "%s\n\n", block.Text)
	case "bullets":
		renderDetailBullets(b, block.Items)
	case "ordered":
		renderOrderedList(b, block.Items)
	case "table":
		renderTable(b, block.Table)
	case "env_table":
		renderEnvTable(b, manifest, block.EnvVars)
	}
}
