package main

import (
	"fmt"
	"strings"
)

func renderMarkdown(manifest Manifest) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# %s\n\n", manifest.Title)
	b.WriteString("<!-- Generated by go run ./tools/configreference -write-doc. Do not edit by hand. -->\n\n")
	b.WriteString("Executable SSOT: [`config-reference.riido.json`](config-reference.riido.json).\n\n")
	fmt.Fprintf(&b, "Evidence artifact: `%s`.\n\n", manifest.EvidenceArtifact)
	fmt.Fprintf(&b, "%s\n\n", manifest.Purpose)
	renderSections(&b, manifest.Sections)
	renderEnvVars(&b, manifest.DaemonEnvVars)
	renderAnchors(&b, manifest.CoverageAnchors)
	renderAssertions(&b, manifest.Assertions)
	return b.String()
}

func renderSections(b *strings.Builder, sections []Section) {
	b.WriteString("## Focused Sections\n\n")
	for _, section := range sections {
		fmt.Fprintf(b, "- [%s](%s)\n", section.Title, section.Path)
	}
	b.WriteByte('\n')
}

func renderEnvVars(b *strings.Builder, rows []EnvVar) {
	b.WriteString("## Daemon Env Catalog\n\n")
	b.WriteString("| Variable | Consumer | Default | Meaning |\n| --- | --- | --- | --- |\n")
	for _, row := range rows {
		fmt.Fprintf(b, "| `%s` | %s | %s | %s |\n", row.Name, row.Consumer, row.Default, row.Meaning)
	}
	b.WriteByte('\n')
}
