package main

import (
	"bytes"
	"fmt"
)

func render(manifest Manifest) string {
	var b bytes.Buffer
	fmt.Fprintf(&b, "# %s\n\n", manifest.Title)
	b.WriteString("<!-- Generated by go run ./tools/sessionlifecycle -write-doc. Do not edit by hand. -->\n\n")
	b.WriteString("[Back to adapter-draft-fields.md](../adapter-draft-fields.md)\n\n")
	b.WriteString("Executable SSOT: [`session-lifecycle.riido.json`](session-lifecycle.riido.json).\n\n")
	fmt.Fprintf(&b, "Evidence artifact: `%s`.\n\n", manifest.EvidenceArtifact)
	writeSteps(&b, manifest.Steps)
	writeAbsentSurfaces(&b, manifest.AbsentSurfaces)
	writeAssertions(&b, manifest.Assertions)
	return b.String()
}

func writeSteps(b *bytes.Buffer, steps []Step) {
	b.WriteString("## Steps\n\n| Step | Status | Responsibility |\n| --- | --- | --- |\n")
	for _, row := range steps {
		fmt.Fprintf(b, "| `%s` | `%s` | %s |\n", row.Step, row.Status, row.Responsibility)
	}
}
