package main

import (
	"fmt"
	"strings"
)

func renderDoc(title, back string, body func(*strings.Builder)) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# %s\n\n", title)
	fmt.Fprintln(&b, "<!-- Generated by go run ./tools/storedistributiondocs -write-doc. Do not edit by hand. -->")
	fmt.Fprintln(&b)
	if back != "" {
		fmt.Fprintf(&b, "[Back to %s](%s)\n\n", back, backPath(back))
	}
	body(&b)
	return b.String()
}

func backPath(label string) string {
	switch label {
	case "store-distribution.md":
		return "../store-distribution.md"
	case "architecture":
		return "../architecture.md"
	case "Daemon Changes":
		return "../daemon-changes.md"
	default:
		return "../store-distribution.md"
	}
}

func writeBullets(b *strings.Builder, items []string) {
	for _, item := range items {
		fmt.Fprintf(b, "- %s\n", item)
	}
}
