package main

import (
	"bytes"
	"fmt"
)

func render(manifest Manifest) string {
	var b bytes.Buffer
	fmt.Fprintf(&b, "# %s\n\n", manifest.Title)
	b.WriteString("<!-- Generated by go run ./tools/eventauthority -write-doc. Do not edit by hand. -->\n\n")
	b.WriteString("Executable SSOT: [`event-ingestor-contract.riido.json`](event-ingestor-contract.riido.json).\n\n")
	fmt.Fprintf(&b, "Evidence artifact: `%s`.\n\n", manifest.EvidenceArtifact)
	b.WriteString("EventIngestor owns CanonicalEvent envelope completion and validation.\n\n")
	writeList(&b, "Draft-Supplied Fields", manifest.DraftSuppliedFields)
	writeList(&b, "Ingestor-Assigned Fields", manifest.IngestorAssignedFields)
	writeList(&b, "Rules", manifest.Rules)
	b.WriteString("Adapters observe provider output and do not append CanonicalEvent directly.\n")
	return b.String()
}

func writeList(b *bytes.Buffer, title string, values []string) {
	fmt.Fprintf(b, "## %s\n\n", title)
	for _, value := range values {
		fmt.Fprintf(b, "- `%s`\n", value)
	}
	b.WriteString("\n")
}
