package main

import (
	"bytes"
	"fmt"
)

func render(manifest Manifest) string {
	var b bytes.Buffer
	fmt.Fprintf(&b, "# %s\n\n", manifest.Title)
	b.WriteString("<!-- Generated by go run ./tools/approvaltimeout -write-doc. Do not edit by hand. -->\n\n")
	b.WriteString("[Back to adapter-draft-fields.md](../adapter-draft-fields.md)\n\n")
	b.WriteString("Executable SSOT: [`approval-wait-timeout.riido.json`](approval-wait-timeout.riido.json).\n\n")
	fmt.Fprintf(&b, "Evidence artifact: `%s`.\n\n", manifest.EvidenceArtifact)
	writeRules(&b, manifest)
	writeSourceChecks(&b, manifest.SourceChecks)
	writeAssertions(&b, manifest.Assertions)
	return b.String()
}

func writeRules(b *bytes.Buffer, manifest Manifest) {
	b.WriteString("## Ownership Rules\n\n")
	fmt.Fprintf(b, "- `%s` maps to `%s`.\n", manifest.ApprovalEvent.EventKind, manifest.ApprovalEvent.EventType)
	fmt.Fprintf(b, "- `%s` is semantic activity and resets `SemanticIdle`.\n", manifest.ApprovalEvent.EventKind)
	b.WriteString("- Approval wait remains bounded by `SemanticIdle` and `HardTimeout`.\n")
	fmt.Fprintf(b, "- `%s` reduces to `%s` and `%s`.\n",
		manifest.TimeoutEvent.EventKind, manifest.TimeoutEvent.ResultStatus, manifest.TimeoutEvent.CancelCommand)
}
