package main

import (
	"fmt"
	"strings"
)

const generatedHeader = "<!-- Generated by go run ./tools/releaseartifacts -write-doc. Do not edit by hand. -->"

func renderDoc(title, back string, body func(*strings.Builder)) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# %s\n\n%s\n\n", title, generatedHeader)
	if back != "" {
		fmt.Fprintf(&b, "[Back to Release Artifacts](%s)\n\n", back)
	}
	body(&b)
	return strings.TrimRight(b.String(), "\n") + "\n"
}

func writeBullets(b *strings.Builder, items []string) {
	for _, item := range items {
		fmt.Fprintf(b, "- %s\n", item)
	}
	b.WriteByte('\n')
}

func codeList(items []string) string {
	quoted := make([]string, 0, len(items))
	for _, item := range items {
		quoted = append(quoted, "`"+item+"`")
	}
	return strings.Join(quoted, ", ")
}
